<?php

return [
    'max_file_size_kb' => (int) env('CUSTOMER_IMPORT_MAX_FILE_SIZE_KB', 20480),
    'max_rows' => (int) env('CUSTOMER_IMPORT_MAX_ROWS', 100000),
    'preview_rows' => (int) env('CUSTOMER_IMPORT_PREVIEW_ROWS', 20),
    'allowed_extensions' => ['xlsx', 'xls', 'csv', 'ods'],
    'allowed_mime_types' => [
        'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
        'application/vnd.ms-excel',
        'application/vnd.oasis.opendocument.spreadsheet',
        'text/csv',
        'text/plain',
        'application/csv',
        'application/octet-stream',
    ],
    'formula_prefixes' => ['=', '+', '-', '@'],
    'profiles' => [
        'Customer Invoice Details' => [
            'worksheet' => 'Customer Invoice Details',
            'source_name' => 'Customer Invoice Details',
            'source_url' => 'https://neogiga.com/admin/customer-imports/source/customer-invoice-details',
            'source_page_url' => 'https://neogiga.com/admin/customer-imports/profile/customer-invoice-details',
            'license_note' => 'Customer-provided business transaction record; restricted internal use.',
            'columns' => [
                'Invoice ID' => 'external_invoice_id',
                'Salesorder Filed Date' => 'invoice_or_sales_order_date',
                'Customer Account Address' => 'address_line_1',
                'Customer Account City' => 'city',
                'Customer Account Country' => 'account_country_name',
                'Customer Account Name' => 'company_name',
                'Customer Account Postal Code .' => 'postal_code',
                'Customer Account Region' => 'source_region_name',
                'Customer Contact Email' => 'contact_email',
                'Customer Contact Name .' => 'contact_name',
                'Customer Contact Telephone Nbr' => 'contact_phone',
                'Customer Country Text' => 'source_country_text',
            ],
            'aliases' => [
                'external_invoice_id' => ['Invoice ID', 'Invoice Id', 'Invoice Number'],
                'invoice_or_sales_order_date' => ['Salesorder Filed Date', 'Sales Order Filed Date', 'Invoice Date'],
                'address_line_1' => ['Customer Account Address', 'Address'],
                'city' => ['Customer Account City', 'City'],
                'account_country_name' => ['Customer Account Country', 'Account Country'],
                'company_name' => ['Customer Account Name', 'Company Name'],
                'postal_code' => ['Customer Account Postal Code .', 'Customer Account Postal Code', 'Postal Code'],
                'source_region_name' => ['Customer Account Region', 'Region'],
                'contact_email' => ['Customer Contact Email', 'Email'],
                'contact_name' => ['Customer Contact Name .', 'Customer Contact Name', 'Contact Name'],
                'contact_phone' => ['Customer Contact Telephone Nbr', 'Customer Contact Telephone Number', 'Phone'],
                'source_country_text' => ['Customer Country Text', 'Country Text'],
            ],
            'required' => [
                'external_invoice_id',
                'company_name',
                'contact_name',
                'contact_email',
                'account_country_name',
            ],
        ],
    ],
    'canonical_country_fallbacks' => [
        'LK' => [
            'name' => 'Sri Lanka',
            'iso_code_2' => 'LK',
            'iso_code_3' => 'LKA',
            'phone_code' => '+94',
            'region' => 'Asia',
            'subregion' => 'Southern Asia',
            'aliases' => ['SRI LANKA', 'SRI-LANKA', 'LK', 'LKA'],
        ],
    ],
    'default_marketing_status' => 'unknown',
    'default_transactional_eligibility' => true,
];
