<?php

return [
    'source_code' => 'elecforest',
    'source_name' => 'ElecForest',
    'source_url' => 'https://elecforest.com',
    'public_url' => rtrim((string) env('ELECFOREST_PUBLIC_URL', 'https://neogiga.com'), '/'),
    'default_file' => storage_path('app/imports/elecforest-products.jsonl'),
    'queue' => env('ELECFOREST_IMPORT_QUEUE', 'catalog-imports'),
    'image_queue' => env('ELECFOREST_IMAGE_QUEUE', 'catalog-media'),
    'derivative_queue' => env('ELECFOREST_DERIVATIVE_QUEUE', 'catalog-media-derivatives'),
    'image_disk' => env('ELECFOREST_IMAGE_DISK', 'public'),
    'image_directory' => 'products/elecforest',
    'max_image_bytes' => (int) env('ELECFOREST_MAX_IMAGE_BYTES', 10 * 1024 * 1024),
    'max_image_dimension' => (int) env('ELECFOREST_MAX_IMAGE_DIMENSION', 10000),
    'min_image_dimension' => (int) env('ELECFOREST_MIN_IMAGE_DIMENSION', 50),
    'image_timeout' => (int) env('ELECFOREST_IMAGE_TIMEOUT', 20),
    'image_connect_timeout' => (int) env('ELECFOREST_IMAGE_CONNECT_TIMEOUT', 8),
    'image_redirects' => (int) env('ELECFOREST_IMAGE_REDIRECTS', 3),
    'allowed_image_hosts' => array_values(array_filter(array_map(
        static fn (string $host): string => strtolower(trim($host)),
        explode(',', (string) env('ELECFOREST_IMAGE_HOSTS', 'ueeshop.ly200-cdn.com'))
    ))),
    'ignored_image_basenames' => [
        'formatwebp-447d.jpg',
        'logo-dhl.png',
        'logo-fedex.png',
        'logo-ups.png',
        'logo-aramex.png',
        '74b8f14db6.png',
        '12c6bd96d8.png',
        'divider-slim.png',
        'banktransfer-7e3d.png',
        'logo-wise-v2.png',
        'logo-paypal.png',
    ],
    'source_file_label' => 'elecforest-products.jsonl',
    'license_note' => env('ELECFOREST_LICENSE_NOTE', 'Supplier catalogue data; redistribution and media rights require administrator review before public use.'),
    'data_year' => '2026',
    'draft_status' => 'draft',
    'draft_visibility' => 'hidden',
    'review_category_path' => ['Catalog Imports', 'ElecForest Review'],
    'advisory_disclaimer' => 'Advisory only. Verify specifications, compatibility, safety, availability and commercial terms before use or purchase.',
];
