<?php

namespace App\Services\Data\Normalizers;

/**
 * Class ProductDataNormalizer
 * 
 * Normalizes product data from various suppliers into a unified format.
 */
class ProductDataNormalizer
{
    /**
     * Normalize product data from any supplier format.
     */
    public function normalize(array $rawProduct, string $supplier): array
    {
        $normalized = [
            'source_supplier' => $supplier,
            'name' => $this->normalizeName($rawProduct['name'] ?? ''),
            'description' => $this->normalizeDescription($rawProduct['description'] ?? ''),
            'mpn' => $this->normalizeMpn($rawProduct),
            'sku' => $this->normalizeSku($rawProduct['sku'] ?? ''),
            'upc_ean' => $this->normalizeUpcEan($rawProduct['upc'] ?? $rawProduct['ean'] ?? null),
            'brand' => $this->normalizeBrand($rawProduct),
            'category' => $this->normalizeCategory($rawProduct),
            'subcategory' => $this->normalizeSubcategory($rawProduct),
            'technical_specifications' => $this->normalizeSpecifications($rawProduct),
            'features' => $this->normalizeFeatures($rawProduct['features'] ?? []),
            'applications' => $this->normalizeApplications($rawProduct['applications'] ?? []),
            'compatible_boards' => $this->normalizeCompatibleBoards($rawProduct['compatible_boards'] ?? []),
            'related_products' => $rawProduct['related_products'] ?? [],
            'accessories' => $rawProduct['accessories'] ?? [],
            'images' => $this->normalizeImages($rawProduct['images'] ?? []),
            'datasheets' => $this->normalizeDatasheets($rawProduct['documents'] ?? $rawProduct['datasheets'] ?? []),
            'cad_models' => $this->normalizeCadModels($rawProduct['cad_models'] ?? []),
            'libraries' => $this->normalizeLibraries($rawProduct['libraries'] ?? []),
            'github_examples' => $this->normalizeGithubExamples($rawProduct['github_examples'] ?? $rawProduct['examples'] ?? []),
            'documentation_links' => $this->normalizeDocumentationLinks($rawProduct['documentation'] ?? []),
            'pricing' => $this->normalizePricing($rawProduct),
            'inventory' => $this->normalizeInventory($rawProduct),
            'seo' => $this->generateSeoFields($rawProduct),
            'ai_summary' => null, // To be generated by AI service
            'metadata' => [
                'imported_at' => now(),
                'last_updated' => now(),
                'import_source' => $supplier,
                'raw_data_hash' => md5(json_encode($rawProduct)),
            ],
        ];

        return $normalized;
    }

    /**
     * Normalize product name.
     */
    protected function normalizeName(string $name): string
    {
        return trim(preg_replace('/\s+/', ' ', $name));
    }

    /**
     * Normalize product description.
     */
    protected function normalizeDescription(string $description): string
    {
        // Remove excessive whitespace and normalize line breaks
        $description = preg_replace('/\r\n/', "\n", $description);
        $description = preg_replace('/\n{3,}/', "\n\n", $description);
        return trim($description);
    }

    /**
     * Extract and normalize MPN (Manufacturer Part Number).
     */
    protected function normalizeMpn(array $rawProduct): string
    {
        return $rawProduct['mpn'] 
            ?? $rawProduct['manufacturer_part_number'] 
            ?? $rawProduct['part_number']
            ?? $rawProduct['sku'] 
            ?? '';
    }

    /**
     * Normalize SKU.
     */
    protected function normalizeSku(string $sku): string
    {
        return strtoupper(trim($sku));
    }

    /**
     * Normalize UPC/EAN.
     */
    protected function normalizeUpcEan(?string $code): ?string
    {
        if (!$code) {
            return null;
        }
        
        // Remove hyphens and spaces
        $code = preg_replace('/[\-\s]/', '', $code);
        
        // Validate length (UPC: 12, EAN: 13)
        if (strlen($code) === 12 || strlen($code) === 13) {
            return $code;
        }
        
        return null;
    }

    /**
     * Normalize brand information.
     */
    protected function normalizeBrand(array $rawProduct): array
    {
        $brand = $rawProduct['brand'] ?? [];
        
        if (is_string($brand)) {
            return ['name' => $brand];
        }
        
        return [
            'name' => $brand['name'] ?? 'Unknown',
            'manufacturer' => $brand['manufacturer'] ?? null,
            'logo' => $brand['logo'] ?? null,
            'website' => $brand['website'] ?? null,
        ];
    }

    /**
     * Normalize category hierarchy.
     */
    protected function normalizeCategory(array $rawProduct): array
    {
        $category = $rawProduct['category'] ?? 'Uncategorized';
        
        if (is_string($category)) {
            return ['name' => $category, 'slug' => str_slug($category)];
        }
        
        return [
            'id' => $category['id'] ?? null,
            'name' => $category['name'] ?? 'Uncategorized',
            'slug' => $category['slug'] ?? str_slug($category['name'] ?? 'uncategorized'),
            'parent_id' => $category['parent_id'] ?? null,
            'path' => $category['path'] ?? null,
        ];
    }

    /**
     * Normalize subcategory.
     */
    protected function normalizeSubcategory(array $rawProduct): ?array
    {
        $subcategory = $rawProduct['subcategory'] ?? null;
        
        if (!$subcategory) {
            return null;
        }
        
        if (is_string($subcategory)) {
            return ['name' => $subcategory, 'slug' => str_slug($subcategory)];
        }
        
        return [
            'id' => $subcategory['id'] ?? null,
            'name' => $subcategory['name'] ?? null,
            'slug' => $subcategory['slug'] ?? str_slug($subcategory['name'] ?? ''),
            'parent_id' => $subcategory['parent_id'] ?? null,
        ];
    }

    /**
     * Normalize technical specifications into key-value pairs.
     */
    protected function normalizeSpecifications(array $rawProduct): array
    {
        $specs = $rawProduct['specifications'] ?? $rawProduct['specs'] ?? [];
        
        if (!is_array($specs)) {
            return [];
        }
        
        $normalized = [];
        foreach ($specs as $key => $value) {
            $normalizedKey = $this->snakeCase($key);
            $normalized[$normalizedKey] = is_array($value) ? json_encode($value) : $value;
        }
        
        return $normalized;
    }

    /**
     * Normalize features list.
     */
    protected function normalizeFeatures(array $features): array
    {
        return array_map(function($feature) {
            if (is_string($feature)) {
                return trim($feature);
            }
            return $feature['text'] ?? $feature['title'] ?? '';
        }, $features);
    }

    /**
     * Normalize applications/use cases.
     */
    protected function normalizeApplications(array $applications): array
    {
        return array_map('trim', $applications);
    }

    /**
     * Normalize compatible boards list.
     */
    protected function normalizeCompatibleBoards(array $boards): array
    {
        return array_map(function($board) {
            if (is_string($board)) {
                return ['name' => $board];
            }
            return [
                'name' => $board['name'] ?? '',
                'type' => $board['type'] ?? null,
                'version' => $board['version'] ?? null,
            ];
        }, $boards);
    }

    /**
     * Normalize image URLs.
     */
    protected function normalizeImages(array $images): array
    {
        $normalized = [];
        foreach ($images as $image) {
            if (is_string($image)) {
                $normalized[] = ['url' => $image, 'type' => 'main'];
            } elseif (is_array($image)) {
                $normalized[] = [
                    'url' => $image['url'] ?? $image['src'] ?? '',
                    'type' => $image['type'] ?? 'main',
                    'alt' => $image['alt'] ?? null,
                    'order' => $image['order'] ?? 0,
                ];
            }
        }
        return $normalized;
    }

    /**
     * Normalize datasheet/document URLs.
     */
    protected function normalizeDatasheets(array $documents): array
    {
        $normalized = [];
        foreach ($documents as $doc) {
            if (is_string($doc)) {
                $normalized[] = ['url' => $doc, 'type' => 'datasheet'];
            } elseif (is_array($doc)) {
                $normalized[] = [
                    'url' => $doc['url'] ?? $doc['link'] ?? '',
                    'type' => $doc['type'] ?? 'datasheet',
                    'title' => $doc['title'] ?? null,
                    'language' => $doc['language'] ?? 'en',
                ];
            }
        }
        return $normalized;
    }

    /**
     * Normalize CAD/3D model URLs.
     */
    protected function normalizeCadModels(array $models): array
    {
        $normalized = [];
        foreach ($models as $model) {
            if (is_string($model)) {
                $normalized[] = ['url' => $model, 'format' => 'unknown'];
            } elseif (is_array($model)) {
                $normalized[] = [
                    'url' => $model['url'] ?? $model['link'] ?? '',
                    'format' => $model['format'] ?? $model['type'] ?? 'unknown',
                    'software' => $model['software'] ?? null,
                ];
            }
        }
        return $normalized;
    }

    /**
     * Normalize library information.
     */
    protected function normalizeLibraries(array $libraries): array
    {
        $normalized = [];
        foreach ($libraries as $lib) {
            if (is_string($lib)) {
                $normalized[] = ['name' => $lib, 'platform' => 'unknown'];
            } elseif (is_array($lib)) {
                $normalized[] = [
                    'name' => $lib['name'] ?? '',
                    'platform' => $lib['platform'] ?? $lib['type'] ?? 'unknown',
                    'repository' => $lib['repository'] ?? null,
                    'version' => $lib['version'] ?? null,
                ];
            }
        }
        return $normalized;
    }

    /**
     * Normalize GitHub example repositories.
     */
    protected function normalizeGithubExamples(array $examples): array
    {
        $normalized = [];
        foreach ($examples as $example) {
            if (is_string($example)) {
                $normalized[] = ['url' => $example];
            } elseif (is_array($example)) {
                $normalized[] = [
                    'url' => $example['url'] ?? $example['repository'] ?? '',
                    'title' => $example['title'] ?? null,
                    'description' => $example['description'] ?? null,
                ];
            }
        }
        return $normalized;
    }

    /**
     * Normalize documentation links.
     */
    protected function normalizeDocumentationLinks(array $links): array
    {
        $normalized = [];
        foreach ($links as $link) {
            if (is_string($link)) {
                $normalized[] = ['url' => $link, 'type' => 'documentation'];
            } elseif (is_array($link)) {
                $normalized[] = [
                    'url' => $link['url'] ?? $link['link'] ?? '',
                    'type' => $link['type'] ?? 'documentation',
                    'title' => $link['title'] ?? null,
                ];
            }
        }
        return $normalized;
    }

    /**
     * Normalize pricing information.
     */
    protected function normalizePricing(array $rawProduct): array
    {
        $price = $rawProduct['price'] ?? [];
        
        if (is_numeric($price)) {
            return [
                'base_price' => $price,
                'currency' => $rawProduct['currency'] ?? 'USD',
                'bulk_pricing' => $rawProduct['bulk_pricing'] ?? [],
            ];
        }
        
        return [
            'base_price' => $price['amount'] ?? $price['base'] ?? 0,
            'currency' => $price['currency'] ?? 'USD',
            'sale_price' => $price['sale_amount'] ?? $price['sale'] ?? null,
            'bulk_pricing' => $price['bulk'] ?? $rawProduct['bulk_pricing'] ?? [],
            'country_prices' => $rawProduct['country_prices'] ?? [],
        ];
    }

    /**
     * Normalize inventory information.
     */
    protected function normalizeInventory(array $rawProduct): array
    {
        $inventory = $rawProduct['inventory'] ?? $rawProduct['stock'] ?? [];
        
        if (is_numeric($inventory)) {
            return [
                'quantity' => $inventory,
                'warehouses' => $rawProduct['warehouses'] ?? [],
            ];
        }
        
        return [
            'quantity' => $inventory['quantity'] ?? $inventory['stock'] ?? 0,
            'availability' => $inventory['availability'] ?? $inventory['in_stock'] ?? true,
            'lead_time' => $inventory['lead_time'] ?? null,
            'warehouses' => $inventory['warehouses'] ?? $rawProduct['warehouses'] ?? [],
        ];
    }

    /**
     * Generate SEO fields.
     */
    protected function generateSeoFields(array $rawProduct): array
    {
        $name = $rawProduct['name'] ?? '';
        $mpn = $this->normalizeMpn($rawProduct);
        
        return [
            'meta_title' => substr($name, 0, 60),
            'meta_description' => substr(strip_tags($rawProduct['description'] ?? ''), 0, 160),
            'meta_keywords' => implode(', ', array_slice(explode(' ', $name), 0, 10)),
            'slug' => $this->generateSlug($name, $mpn),
            'canonical_url' => null,
            'og_title' => $name,
            'og_description' => substr(strip_tags($rawProduct['description'] ?? ''), 0, 200),
            'og_image' => collect($rawProduct['images'] ?? [])->first()['url'] ?? null,
        ];
    }

    /**
     * Generate URL slug from name and MPN.
     */
    protected function generateSlug(string $name, string $mpn): string
    {
        $slug = strtolower(preg_replace('/[^a-zA-Z0-9]+/', '-', $name));
        $slug = preg_replace('/-+/', '-', $slug);
        $slug = trim($slug, '-');
        
        if ($mpn) {
            $slug .= '-' . strtolower($mpn);
        }
        
        return $slug;
    }

    /**
     * Convert string to snake_case.
     */
    protected function snakeCase(string $string): string
    {
        return strtolower(preg_replace('/[^a-zA-Z0-9]+/', '_', $string));
    }
}
