<h2>Apply for Seller Early Access</h2>
<p class="muted">Coming Soon / Early Access. This application creates a pending review record only.</p>
<form class="ng-json-form" data-endpoint="/partner-applications/seller" data-partner-kind="seller">
    @csrf
    <input type="hidden" name="source" value="public_sell_on_neogiga">
    <div class="form-grid">
        <div><label>Business name</label><input name="business_name" required></div>
        <div><label>Contact person</label><input name="contact_person" required></div>
        <div><label>Email</label><input name="email" type="email" required></div>
        <div><label>Phone</label><input name="phone" required></div>
        <div><label>WhatsApp</label><input name="whatsapp"></div>
        <div><label>Operating scope</label><select name="operating_scope" required><option value="country">Single country</option><option value="global">Global seller</option></select></div>
        <div><label>Seller base country</label><select name="country_id" data-partner-country required><option value="">Detecting your country…</option></select><small class="muted" data-country-note></small></div>
        <div class="full"><label>Target marketplace countries</label><div class="marketplace-picker" data-marketplace-picker><button class="marketplace-picker__toggle" type="button" data-marketplace-toggle aria-expanded="false">Choose target country</button><div class="marketplace-picker__menu" data-partner-marketplaces hidden></div></div><small class="muted" data-marketplace-note>Select exactly one country for single-country scope, or one or more for global scope.</small></div>
        <div><label>Seller type</label><select name="seller_type" required><option value="">Choose</option><option>manufacturer</option><option>authorized_distributor</option><option>importer</option><option>regional_reseller</option><option>local_electronics_shop</option><option>service_center</option><option>school_lab_supplier</option><option>industrial_supplier</option></select></div>
        <div><label>Business type</label><input name="business_type" placeholder="Company, shop, partnership" required></div>
        <div><label>Monthly order capacity</label><input name="monthly_order_capacity" placeholder="Example: 100 orders"></div>
        <div><label>Approximate annual turnover</label><select name="annual_turnover_range" required><option value="">Choose USD-equivalent range</option><option value="under_25000">Under USD 25,000</option><option value="25000_100000">USD 25,000–100,000</option><option value="100000_500000">USD 100,000–500,000</option><option value="500000_1000000">USD 500,000–1 million</option><option value="1000000_5000000">USD 1–5 million</option><option value="over_5000000">Over USD 5 million</option><option value="prefer_not_to_say">Prefer not to say</option></select></div>
        <div class="full"><label>Website</label><input name="website" type="url" placeholder="https://example.com"></div>
        <div class="full"><label>Product categories</label><input name="product_categories_text" placeholder="Robotics, IoT, solar, tools"></div>
        <div class="full"><label>Brands carried</label><input name="brands_carried_text" placeholder="Arduino, Espressif, Mean Well"></div>
        <div><label>Physical store?</label><select name="has_physical_store"><option value="0">No</option><option value="1">Yes</option></select></div>
        <div><label>Existing inventory?</label><select name="has_existing_inventory"><option value="0">No</option><option value="1">Yes</option></select></div>
        <div class="full"><label>Message</label><textarea name="message"></textarea></div>
    </div>
    <button class="btn btn-primary" type="submit" style="margin-top:14px">Apply for Seller Early Access</button>
    <a class="btn btn-ghost" href="/distributors" style="margin-top:14px">Join Distributor Network</a>
    <p class="notice" data-form-notice></p>
</form>
@once
@push('foot')
<script nonce="{{ $csp_nonce ?? '' }}">
function updatePartnerTargetSummary(form){const checked=[...form.querySelectorAll('[data-partner-marketplaces] input:checked')],toggle=form.querySelector('[data-marketplace-toggle]');toggle.textContent=checked.length===0?'Choose target country':checked.length===1?checked[0].dataset.label:checked.length+' target countries selected'}
function enforcePartnerTargetScope(form,changed){const global=form.querySelector('[name="operating_scope"]').value==='global',checked=[...form.querySelectorAll('[data-partner-marketplaces] input:checked')];if(!global&&checked.length>1){checked.forEach(input=>{if(input!==changed)input.checked=false})}form.querySelector('[data-marketplace-note]').textContent=global?'Select one or more target countries for global scope.':'Select exactly one target country for single-country scope.';updatePartnerTargetSummary(form)}
function populatePartnerTargets(form,marketplaces){const menu=form.querySelector('[data-partner-marketplaces]');menu.innerHTML='';marketplaces.forEach(m=>{const label=document.createElement('label');label.className='marketplace-picker__option';const input=document.createElement('input');input.type='checkbox';input.name='target_marketplace_ids[]';input.value=String(m.id);input.dataset.label=m.country_name;const text=document.createElement('span');text.textContent=m.country_name+' ('+m.country_iso_code_2+') — '+m.name;label.append(input,text);input.addEventListener('change',()=>{enforcePartnerTargetScope(form,input);if(form.querySelector('[name="operating_scope"]').value!=='global'&&input.checked){menu.hidden=true;form.querySelector('[data-marketplace-toggle]').setAttribute('aria-expanded','false')}});menu.append(label)});updatePartnerTargetSummary(form)}
async function loadPartnerCountries(form){const select=form.querySelector('[data-partner-country]'),menu=form.querySelector('[data-partner-marketplaces]'),note=form.querySelector('[data-country-note]'),button=form.querySelector('button[type="submit"]');button.disabled=true;try{const r=await fetch('/partner-country-options',{headers:{Accept:'application/json'}}),j=await r.json();if(!r.ok)throw new Error(j.message||'Country list unavailable');const d=j.data;select.innerHTML='';const countries=d.country_locked&&d.detected_country?[d.detected_country]:d.countries;select.append(new Option(d.country_locked?'Detected base country':'Choose your base country',''));countries.forEach(c=>select.append(new Option(c.name+' ('+c.iso_code_2+')',c.id)));populatePartnerTargets(form,d.marketplaces);if(d.detected_country_id){select.value=String(d.detected_country_id);note.textContent='Detected from your location. This active country is used as your '+form.dataset.partnerKind+' base.'}else{note.textContent='Your location is not an active NeoGiga country. Please choose your '+form.dataset.partnerKind+' base.'}button.disabled=false}catch(err){select.innerHTML='<option value="">Country options unavailable</option>';menu.textContent='Marketplace options unavailable';note.textContent=err.message}}
document.querySelectorAll('.ng-json-form').forEach(form=>{const toggle=form.querySelector('[data-marketplace-toggle]'),menu=form.querySelector('[data-partner-marketplaces]');toggle.addEventListener('click',()=>{menu.hidden=!menu.hidden;toggle.setAttribute('aria-expanded',String(!menu.hidden))});form.querySelector('[name="operating_scope"]').addEventListener('change',()=>enforcePartnerTargetScope(form));document.addEventListener('click',event=>{if(!form.querySelector('[data-marketplace-picker]').contains(event.target)){menu.hidden=true;toggle.setAttribute('aria-expanded','false')}});loadPartnerCountries(form);form.addEventListener('submit',async e=>{e.preventDefault();const notice=form.querySelector('[data-form-notice]'),selected=form.querySelectorAll('[data-partner-marketplaces] input:checked');notice.className='notice';if(selected.length===0||(form.querySelector('[name="operating_scope"]').value!=='global'&&selected.length!==1)){notice.className='notice err';notice.textContent='Choose the required target marketplace country.';return}notice.textContent='Submitting...';const fd=new FormData(form),data={};fd.forEach((v,k)=>{const arrayKey=k.endsWith('[]'),key=arrayKey?k.slice(0,-2):k;if(arrayKey){(data[key]??=[]).push(v)}else{data[key]=v}});['product_categories','brands_carried','current_business_categories'].forEach(k=>{const raw=data[k+'_text'];if(raw){data[k]=raw.split(',').map(x=>x.trim()).filter(Boolean);delete data[k+'_text']}});['has_physical_store','has_existing_inventory','existing_dealer_network','warehouse_available'].forEach(k=>{if(k in data)data[k]=data[k]==='1'});try{const r=await fetch(form.dataset.endpoint,{method:'POST',headers:{'Content-Type':'application/json',Accept:'application/json'},body:JSON.stringify(data)}),j=await r.json();if(!r.ok)throw new Error(j.message||Object.values(j.errors||{})[0]?.[0]||'Submission failed');notice.className='notice ok';notice.textContent='Application submitted. Status: '+j.data.status+'. NeoGiga team will review it.';form.reset();loadPartnerCountries(form)}catch(err){notice.className='notice err';notice.textContent=err.message}})})
</script>
@endpush
@endonce
