@extends('admin.layout')
@section('title', 'AI BOM Builds')
@section('crumb', 'AI Commerce / BOM Builds')

@section('content')
<div class="page-head">
    <div>
        <h2>AI BOM Builds</h2>
        <p>Bill of Materials builds generated by the AI Commerce engine.</p>
    </div>
    <div class="page-actions">
        <a href="/admin/ai-commerce" class="btn btn-ghost">Back to Dashboard</a>
    </div>
</div>

<div class="card">
    <div class="card-h"><h2>BOM Builds ({{ $builds->total() }})</h2></div>
    <div class="scroll-x">
        <table class="tbl">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>User</th>
                    <th>Description</th>
                    <th>Status</th>
                    <th>Items</th>
                    <th>Created</th>
                </tr>
            </thead>
            <tbody>
                @forelse($builds as $build)
                <tr>
                    <td class="num">#{{ $build->id }}</td>
                    <td>{{ $build->user_name ?? '—' }}</td>
                    <td style="max-width:260px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap">{{ $build->description ?? $build->name ?? '—' }}</td>
                    <td>
                        <span class="badge {{ ($build->status ?? '') === 'completed' ? 'b-ok' : 'b-muted' }}">
                            {{ $build->status ?? 'pending' }}
                        </span>
                    </td>
                    <td class="num">{{ $build->item_count ?? '—' }}</td>
                    <td style="white-space:nowrap;font-size:.82rem">{{ $build->created_at?->diffForHumans() ?? '—' }}</td>
                </tr>
                @empty
                <tr>
                    <td colspan="6" class="empty">
                        <p>No BOM builds yet.</p>
                    </td>
                </tr>
                @endforelse
            </tbody>
        </table>
    </div>
    {{ $builds->links() }}
</div>
@endsection
