<?php

namespace App\Services\Bom;

class BomBuilderService
{
    public function normalizeCustomBuild(array $data): array
    {
        return [
            'name' => $data['name'],
            'goal' => $data['goal'] ?? null,
            'budget' => $data['budget'] ?? null,
            'items' => array_values($data['items'] ?? []),
            'source_notes' => 'User-provided build request; no AI recommendation is generated by this endpoint.',
            'confidence_level' => 'medium',
            'last_updated' => now()->toISOString(),
            'disclaimer' => 'Advisory only',
        ];
    }
}
