@extends('admin.layout')
@section('title','POS')
@section('crumb','Operations / Terminals & Sessions')
@section('page_actions')
<details class="modal"><summary class="btn btn-primary">Create Terminal</summary><div class="modal-panel"><div class="modal-h"><h3>Create POS Terminal</h3></div><form class="modal-b form-stack" method="post" action="/admin/pos/terminals">@csrf<div class="form-grid"><div class="field"><label>Name</label><input class="control" name="terminal_name" required></div><div class="field"><label>Code</label><input class="control" name="terminal_code"></div><div class="field"><label>Warehouse</label><select class="control" name="warehouse_id"><option value="">None</option>@foreach($warehouses as $w)<option value="{{ $w->id }}">{{ $w->name }}</option>@endforeach</select></div><div class="field"><label>Status</label><select class="control" name="status"><option>active</option><option>inactive</option></select></div></div><div class="field"><label>Location</label><input class="control" name="location"></div><button class="btn btn-primary" type="submit">Save Terminal</button></form></div></details>
<details class="modal"><summary class="btn btn-ghost">Open Session</summary><div class="modal-panel"><div class="modal-h"><h3>Open Cash Drawer</h3></div><form class="modal-b form-stack" method="post" action="/admin/pos/sessions/open">@csrf<div class="form-grid"><div class="field"><label>Terminal</label><select class="control" name="pos_terminal_id" required>@foreach($terminals as $t)<option value="{{ $t->id }}">{{ $t->terminal_name }}</option>@endforeach</select></div><div class="field"><label>Warehouse</label><select class="control" name="warehouse_id"><option value="">Terminal default</option>@foreach($warehouses as $w)<option value="{{ $w->id }}">{{ $w->name }}</option>@endforeach</select></div><div class="field"><label>Opening cash</label><input class="control" type="number" step="0.01" name="opening_cash" value="0"></div></div><button class="btn btn-primary" type="submit">Open Session</button></form></div></details>
@endsection
@section('content')
<div class="grid kpis"><div class="kpi"><div class="t">Terminals</div><div class="v tnum">{{ number_format($stats['terminals']) }}</div><div class="s">registered</div></div><div class="kpi"><div class="t">Open Sessions</div><div class="v tnum">{{ number_format($stats['openSessions']) }}</div><div class="s">cash drawers</div></div><div class="kpi"><div class="t">Sales</div><div class="v tnum">{{ number_format($stats['sales']) }}</div><div class="s">{{ number_format($stats['paidSales']) }} paid</div></div><div class="kpi"><div class="t">Revenue</div><div class="v tnum">{{ number_format((float)$stats['revenue'],2) }}</div><div class="s">local total</div></div></div>
<div class="grid split"><section class="card"><div class="card-h"><h2>Sessions</h2><span class="badge b-info">open/close</span></div><div class="scroll-x"><table class="tbl"><thead><tr><th>Session</th><th>Warehouse</th><th>Status</th><th>Action</th></tr></thead><tbody>@forelse($sessions as $s)<tr><td class="mono">{{ $s->session_number ?? ('#'.$s->id) }}</td><td>#{{ $s->warehouse_id }}</td><td><span class="badge {{ $s->status==='open'?'b-ok':'b-muted' }}">{{ $s->status }}</span></td><td>@if($s->status==='open')<details class="modal"><summary class="btn btn-ghost">Close</summary><div class="modal-panel"><div class="modal-h"><h3>Close Session</h3></div><form class="modal-b form-stack" method="post" action="/admin/pos/sessions/{{ $s->id }}/close">@csrf<div class="field"><label>Closing cash</label><input class="control" type="number" step="0.01" name="closing_cash"></div><div class="field"><label>Notes</label><textarea class="control" name="notes"></textarea></div><button class="btn btn-primary" type="submit">Close Session</button></form></div></details>@endif</td></tr>@empty<tr><td colspan="4"><div class="empty"><h3>No sessions</h3></div></td></tr>@endforelse</tbody></table></div></section><section class="card"><div class="card-h"><h2>Sales</h2><span class="badge b-warn">refund placeholder</span></div><div class="scroll-x"><table class="tbl"><thead><tr><th>Sale</th><th>Total</th><th>Payment</th><th>Status</th></tr></thead><tbody>@forelse($sales as $s)<tr><td class="mono">{{ $s->sale_reference ?? ('#'.$s->id) }}</td><td class="tnum">{{ number_format((float)$s->total_amount,2) }}</td><td><span class="badge b-muted">{{ $s->payment_status }}</span></td><td>{{ $s->status }}</td></tr>@empty<tr><td colspan="4"><div class="empty"><h3>No sales</h3></div></td></tr>@endforelse</tbody></table></div></section></div>
<section class="card stack-gap"><div class="card-h"><h2>Terminals</h2><span class="badge b-info">offline sync placeholder</span></div><div class="scroll-x"><table class="tbl"><thead><tr><th>Name</th><th>Code</th><th>Warehouse</th><th>Status</th></tr></thead><tbody>@forelse($terminals as $t)<tr><td>{{ $t->terminal_name }}</td><td class="mono">{{ $t->terminal_code }}</td><td>#{{ $t->warehouse_id }}</td><td><span class="badge {{ $t->status==='active'?'b-ok':'b-muted' }}">{{ $t->status }}</span></td></tr>@empty<tr><td colspan="4"><div class="empty"><h3>No terminals</h3></div></td></tr>@endforelse</tbody></table></div></section>
@endsection
