@extends('admin.layout')
@section('title','Marketing Analytics')
@section('crumb','Events, top searches and trending placeholders')
@section('content')
<div class="card"><div class="card-h"><h2>Analytics Events</h2><span class="sub">Consent-aware endpoint foundation</span></div><div class="scroll-x"><table class="tbl"><thead><tr><th>Event</th><th>Type</th><th>Occurred</th></tr></thead><tbody>@forelse($events as $e)<tr><td><strong>{{ $e->event_name }}</strong></td><td>{{ $e->event_type }}</td><td>{{ $e->occurred_at ?? $e->created_at }}</td></tr>@empty<tr><td colspan="3"><div class="empty"><h3>No events yet</h3></div></td></tr>@endforelse</tbody></table></div>@if($events->hasPages())<div style="padding:12px 16px;border-top:1px solid var(--line)">{{ $events->links() }}</div>@endif</div>
<div class="card" style="margin-top:16px"><div class="card-h"><h2>Top Searches</h2></div><div class="scroll-x"><table class="tbl"><thead><tr><th>Term</th><th class="num">Count</th></tr></thead><tbody>@forelse($topSearches as $s)<tr><td>{{ $s->term }}</td><td class="num tnum">{{ number_format($s->search_count) }}</td></tr>@empty<tr><td colspan="2"><div class="empty"><h3>No searches yet</h3></div></td></tr>@endforelse</tbody></table></div></div>
<div class="card" style="margin-top:16px"><div class="card-h"><h2>Campaign Delivery</h2><span class="sub">Email campaigns and newsletters · provider-verified events only</span></div><div class="scroll-x"><table class="tbl"><thead><tr><th>Campaign</th><th>Channel</th><th>Planned</th><th>Eligible</th><th>Sent</th><th>Delivered</th><th>Delivery rate</th><th>Bounces</th><th>Complaints</th><th>Unsubscribes</th></tr></thead><tbody>@forelse($campaignPerformance as $campaign)<tr><td><strong>{{ $campaign['name'] }}</strong><div class="sub">{{ $campaign['status'] }}</div></td><td>{{ str_replace('_', ' ', $campaign['channel']) }}</td><td>{{ number_format($campaign['planned']) }}</td><td>{{ number_format($campaign['eligible']) }}</td><td>{{ number_format($campaign['sent']) }}</td><td>{{ number_format($campaign['delivered']) }}</td><td>{{ $campaign['delivery_rate'] }}%</td><td>{{ number_format($campaign['hard_bounces'] + $campaign['soft_bounces']) }}</td><td>{{ number_format($campaign['complaints']) }}</td><td>{{ number_format($campaign['unsubscribes']) }}</td></tr>@empty<tr><td colspan="10"><div class="empty"><h3>No campaign delivery data</h3></div></td></tr>@endforelse</tbody></table></div></div>
<div class="card" style="margin-top:16px"><div class="card-h"><h2>Country Audiences</h2><span class="sub">Eligibility recalculates before sending</span></div><div class="scroll-x"><table class="tbl"><thead><tr><th>Country</th><th>Contacts</th><th>Potentially marketable</th><th>Transactional / unknown</th><th>Suppressed</th><th>Campaigns</th><th>Last order</th></tr></thead><tbody>@forelse($countryPerformance as $country)<tr><td><strong>{{ $country['name'] }}</strong><div class="sub">{{ $country['iso_code_2'] }}</div></td><td>{{ number_format($country['contact_count']) }}</td><td>{{ number_format($country['potentially_marketable']) }}</td><td>{{ number_format($country['transactional_or_unknown']) }}</td><td>{{ number_format($country['suppressed_count']) }}</td><td>{{ number_format($country['campaigns_sent']) }}</td><td>{{ $country['last_order_activity'] ?? '—' }}</td></tr>@empty<tr><td colspan="7"><div class="empty"><h3>No country audience data</h3></div></td></tr>@endforelse</tbody></table></div></div>
@endsection
