@extends('admin.layout')
@section('title','CRM & Segments')
@section('crumb','Customers, consent, lists and audiences')
@section('content')

<div class="tabs"><a class="tab active" href="#customers">Customers</a><a class="tab" href="#companies">Companies</a><a class="tab" href="#contacts">Contacts</a><a class="tab" href="#countries">Countries</a><a class="tab" href="#segments">Segments</a><a class="tab" href="#consent">Consent</a><a class="tab" href="#suppression">Suppression</a><a class="tab" href="#merge-review">Merge review</a><a class="tab" href="#communications">Communication history</a>@if(auth()->user()?->hasPermission('customers.export'))<a class="tab" href="/admin/marketing/customers/export">Export authorized fields</a>@endif</div>

<div class="card" style="margin-bottom:16px">
    <div class="card-h"><h2>Customer Filters</h2><div class="sub">Marketplace, country, consent and identity search</div></div>
    <form method="get" action="/admin/marketing/crm" style="padding:16px;display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:12px;align-items:end">
        <label>Marketplace<br><select name="marketplace" style="width:100%;height:38px;border:1px solid var(--line);border-radius:7px;padding:0 10px"><option value="">All authorized marketplaces</option>@foreach($marketplaces as $marketplace)<option value="{{ $marketplace->id }}" @selected((string) request('marketplace') === (string) $marketplace->id)>{{ $marketplace->name }} ({{ $marketplace->code }})</option>@endforeach</select></label>
        <label>Country<br><select name="country" style="width:100%;height:38px;border:1px solid var(--line);border-radius:7px;padding:0 10px"><option value="">All countries</option>@foreach($countries as $country)<option value="{{ $country->id }}" @selected((string) request('country') === (string) $country->id)>{{ $country->name }} ({{ $country->iso_code_2 }})</option>@endforeach</select></label>
        <label>Consent state<br><select name="consent_state" style="width:100%;height:38px;border:1px solid var(--line);border-radius:7px;padding:0 10px"><option value="">All states</option>@foreach(['opted_in' => 'Opted in', 'transactional_only' => 'Transactional only', 'unknown' => 'Unknown / review', 'unsubscribed' => 'Unsubscribed'] as $value => $label)<option value="{{ $value }}" @selected(request('consent_state') === $value)>{{ $label }}</option>@endforeach</select></label>
        <label>Company, contact or email<br><input name="q" value="{{ request('q') }}" maxlength="190" placeholder="Search" style="width:100%;height:38px;border:1px solid var(--line);border-radius:7px;padding:0 10px"></label>
        <div style="display:flex;gap:8px"><button class="btn btn-primary" type="submit">Apply filters</button><a class="btn btn-ghost" href="/admin/marketing/crm">Reset</a></div>
    </form>
</div>

<div class="card" style="margin-bottom:16px">
    <div class="card-h"><h2>Create Segment</h2><div class="sub">Validated admin action</div></div>
    <form method="post" action="/admin/marketing/segments" style="padding:16px;display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:12px;align-items:end">
        @csrf
        <label>Name<br><input name="name" required maxlength="190" style="width:100%;height:38px;border:1px solid var(--line);border-radius:7px;padding:0 10px"></label>
        <label>Country<br><select name="country_id" style="width:100%;height:38px;border:1px solid var(--line);border-radius:7px;padding:0 10px"><option value="">Any</option>@foreach($countries as $country)<option value="{{ $country->id }}">{{ $country->name }} ({{ $country->iso_code_2 }})</option>@endforeach</select></label>
        <label>Customer type<br><input name="customer_type" maxlength="60" placeholder="b2b" style="width:100%;height:38px;border:1px solid var(--line);border-radius:7px;padding:0 10px"></label>
        <label>Lifecycle<br><input name="lifecycle_stage" maxlength="60" placeholder="lead" style="width:100%;height:38px;border:1px solid var(--line);border-radius:7px;padding:0 10px"></label>
        <label>Status<br><input name="status" maxlength="60" placeholder="active" style="width:100%;height:38px;border:1px solid var(--line);border-radius:7px;padding:0 10px"></label>
        <label style="display:flex;gap:8px;align-items:center"><input type="checkbox" name="marketing_opt_in" value="1"> Email opt-in</label>
        <label style="display:flex;gap:8px;align-items:center"><input type="checkbox" name="whatsapp_opt_in" value="1"> WhatsApp opt-in</label>
        <label style="display:flex;gap:8px;align-items:center"><input type="checkbox" name="marketing_eligible" value="1"> Valid, consented, unsuppressed email</label>
        <button class="btn btn-primary" type="submit">Create Segment</button>
    </form>
</div>

<div class="grid kpis">
 <div class="kpi"><div class="t">Customers</div><div class="v tnum">{{ number_format($customers->total()) }}</div><div class="s">profiles</div></div>
 <div class="kpi"><div class="t">Segments</div><div class="v tnum">{{ number_format($segments->count()) }}</div><div class="s">dynamic/static</div></div>
 <div class="kpi"><div class="t">Contact lists</div><div class="v tnum">{{ number_format($contactLists->count()) }}</div><div class="s">email/WhatsApp</div></div>
 <div class="kpi"><div class="t">Suppressed</div><div class="v tnum">{{ number_format($suppressed) }}</div><div class="s">do-not-contact</div></div>
</div>
<div class="card" id="customers"><div class="card-h"><h2>Customer Profiles</h2><span class="sub">Permission-scoped customer view</span></div><div class="scroll-x"><table class="tbl"><thead><tr><th>Name</th><th>Email</th><th>Phone</th><th>Type</th><th>Stage</th><th>Opt-in</th></tr></thead><tbody>
@forelse($customers as $c)<tr><td><strong>{{ trim(($c->first_name ?? '').' '.($c->last_name ?? '')) ?: '—' }}</strong></td><td class="mono">{{ $c->email ?? '—' }}</td><td>{{ $c->phone ?? $c->whatsapp_number ?? '—' }}</td><td>{{ $c->customer_type ?? 'retail' }}</td><td><span class="badge b-muted">{{ str_replace('_',' ', $c->lifecycle_stage ?? 'lead') }}</span></td><td>@if($c->marketing_opt_in)<span class="badge b-ok">Email</span>@else<span class="badge b-muted">No</span>@endif</td></tr>@empty<tr><td colspan="6"><div class="empty"><h3>No CRM profiles yet</h3><p>Profiles are created from registrations, OTP login, imports, and campaign forms.</p></div></td></tr>@endforelse
</tbody></table></div>@if($customers->hasPages())<div style="padding:12px 16px;border-top:1px solid var(--line)">{{ $customers->links() }}</div>@endif</div>
<div class="card" id="companies" style="margin-top:16px"><div class="card-h"><h2>Companies</h2><span class="sub">Latest 50 normalized accounts</span></div><div class="scroll-x"><table class="tbl"><thead><tr><th>Company</th><th>Country</th><th>Domain</th><th>Status</th><th>Source</th></tr></thead><tbody>@forelse($accounts as $account)<tr><td><strong>{{ $account->legal_name }}</strong></td><td>{{ $account->country_name ?? '—' }}</td><td class="mono">{{ $account->primary_domain ?? '—' }}</td><td>{{ $account->status }}</td><td>{{ $account->source_name ?? '—' }}</td></tr>@empty<tr><td colspan="5"><div class="empty"><h3>No company accounts</h3></div></td></tr>@endforelse</tbody></table></div></div>
<div class="card" id="contacts" style="margin-top:16px"><div class="card-h"><h2>Contacts</h2><span class="sub">Latest 50 contact people</span></div><div class="scroll-x"><table class="tbl"><thead><tr><th>Contact</th><th>Company</th><th>Email</th><th>Country</th><th>Marketing</th><th>Transactional</th></tr></thead><tbody>@forelse($contacts as $contact)<tr><td><strong>{{ $contact->full_name }}</strong><div class="sub">Source: {{ $contact->original_full_name }}</div></td><td>{{ $contact->company_name ?? '—' }}</td><td class="mono">{{ $contact->email ?? '—' }}</td><td>#{{ $contact->country_id ?? '—' }}</td><td><span class="badge b-muted">{{ $contact->marketing_status }}</span></td><td><span class="badge {{ $contact->transactional_eligible ? 'b-ok' : 'b-warn' }}">{{ $contact->transactional_eligible ? 'Eligible' : 'Blocked' }}</span></td></tr>@empty<tr><td colspan="6"><div class="empty"><h3>No contacts</h3></div></td></tr>@endforelse</tbody></table></div></div>
<div class="card" id="countries" style="margin-top:16px"><div class="card-h"><h2>Country Summary</h2><span class="sub">Company, contact and consent totals</span></div><div class="scroll-x"><table class="tbl"><thead><tr><th>Country</th><th>Companies</th><th>Contacts</th><th>Valid email</th><th>Opted in</th><th>Transactional / unknown</th><th>Invoices</th><th>Last invoice</th></tr></thead><tbody>@forelse($countrySummary as $country)<tr><td><strong>{{ $country->name }}</strong><div class="sub">{{ $country->iso_code_2 }} · {{ $country->region }}</div></td><td>{{ number_format($country->companies) }}</td><td>{{ number_format($country->contacts) }}</td><td>{{ number_format($country->valid_emails) }}</td><td>{{ number_format($country->opted_in) }}</td><td>{{ number_format($country->transactional_or_unknown) }}</td><td>{{ number_format($country->invoices) }}</td><td>{{ $country->last_invoice ?? '—' }}</td></tr>@empty<tr><td colspan="8"><div class="empty"><h3>No country data</h3></div></td></tr>@endforelse</tbody></table></div></div>
<div class="card" id="segments" style="margin-top:16px"><div class="card-h"><h2>Segments</h2></div><div class="scroll-x"><table class="tbl"><thead><tr><th>Name</th><th>Type</th><th>Status</th><th>Last refresh</th><th></th></tr></thead><tbody>@foreach($segments as $s)<tr><td><strong>{{ $s->name }}</strong></td><td>{{ $s->type }}</td><td>@if($s->is_active)<span class="badge b-ok">Active</span>@else<span class="badge b-muted">Inactive</span>@endif</td><td>{{ $s->last_refreshed_at ?? '—' }}</td><td><form method="post" action="/admin/marketing/segments/{{ $s->id }}/refresh">@csrf<button class="btn btn-ghost" type="submit">Refresh</button></form></td></tr>@endforeach</tbody></table></div></div>
<div class="grid split" style="margin-top:16px"><div class="card" id="consent"><div class="card-h"><h2>Consent Evidence</h2></div><div class="scroll-x"><table class="tbl"><thead><tr><th>Email</th><th>Purpose</th><th>Status</th><th>Source</th><th>Recorded</th></tr></thead><tbody>@forelse($consents as $consent)<tr><td class="mono">{{ $consent->email ?? '—' }}</td><td>{{ $consent->purpose }}</td><td>{{ $consent->status ?? ($consent->granted ? 'granted' : 'not granted') }}</td><td>{{ $consent->source ?? '—' }}</td><td>{{ $consent->recorded_at ?? $consent->created_at }}</td></tr>@empty<tr><td colspan="5"><div class="empty"><h3>No consent records</h3></div></td></tr>@endforelse</tbody></table></div></div><div class="card" id="suppression"><div class="card-h"><h2>Active Suppression</h2></div><div class="scroll-x"><table class="tbl"><thead><tr><th>Email</th><th>Reason</th><th>Scope</th><th>Source</th><th>Since</th></tr></thead><tbody>@forelse($suppressions as $suppression)<tr><td class="mono">{{ $suppression->email ?? '—' }}</td><td>{{ $suppression->reason_code ?? $suppression->reason }}</td><td>{{ $suppression->message_scope ?? 'marketing' }}</td><td>{{ $suppression->source ?? '—' }}</td><td>{{ $suppression->suppressed_at ?? $suppression->created_at }}</td></tr>@empty<tr><td colspan="5"><div class="empty"><h3>No active suppressions</h3></div></td></tr>@endforelse</tbody></table></div></div></div>
<div class="grid split" style="margin-top:16px"><div class="card" id="merge-review"><div class="card-h"><h2>Duplicate / Conflict Review</h2></div><div class="scroll-x"><table class="tbl"><thead><tr><th>Import</th><th>Row</th><th>Action</th><th>Country conflict</th></tr></thead><tbody>@forelse($mergeReview as $row)<tr><td>#{{ $row->customer_import_id }}</td><td>{{ $row->row_number }}</td><td>{{ $row->action }}</td><td>{{ $row->country_conflict ? 'Yes' : 'No' }}</td></tr>@empty<tr><td colspan="4"><div class="empty"><h3>No ambiguous records</h3></div></td></tr>@endforelse</tbody></table></div></div><div class="card" id="communications"><div class="card-h"><h2>Communication History</h2></div><div class="scroll-x"><table class="tbl"><thead><tr><th>Event</th><th>Class</th><th>Status</th><th>Provider</th><th>Updated</th></tr></thead><tbody>@forelse($communicationHistory as $log)<tr><td>{{ $log->event_type }}</td><td>{{ $log->message_class }}</td><td>{{ $log->status }}</td><td>{{ $log->provider ?? '—' }}</td><td>{{ $log->updated_at }}</td></tr>@empty<tr><td colspan="5"><div class="empty"><h3>No communication history</h3></div></td></tr>@endforelse</tbody></table></div></div></div>
@endsection
