@extends('admin.layout')
@section('title','Customer Import Report')
@section('crumb','Customer Management / Import History')
@section('content')
<div class="card" style="margin-bottom:16px"><div class="card-h"><h2>{{ $import->original_file_name }}</h2><span class="badge {{ $import->status === 'completed' ? 'b-ok' : 'b-warn' }}">{{ $import->status }}</span></div><div style="padding:16px;display:grid;grid-template-columns:repeat(auto-fit,minmax(170px,1fr));gap:12px">
@foreach(['worksheet','source_name','started_at','completed_at','total_rows','valid_rows','imported_rows','updated_rows','duplicate_rows','warning_rows','error_rows','unresolved_countries','consent_state'] as $field)<div><span class="sub">{{ str_replace('_',' ',ucfirst($field)) }}</span><br><strong>{{ $import->{$field} ?? '—' }}</strong></div>@endforeach
</div></div>
<div style="display:flex;justify-content:flex-end;margin-bottom:12px"><a class="btn btn-ghost" href="/admin/marketing/customer-imports/{{ $import->id }}/errors.csv">Download error report</a></div>
<div class="card" style="margin-bottom:16px"><div class="card-h"><h2>Rows</h2></div><div class="scroll-x"><table class="tbl"><thead><tr><th>Row</th><th>Status</th><th>Action</th><th>Country</th><th>Account</th><th>Contact</th><th>Invoice</th></tr></thead><tbody>@foreach($rows as $row)<tr><td>{{ $row->row_number }}</td><td>{{ $row->status }}</td><td>{{ $row->action ?? '—' }}</td><td>{{ $row->resolved_country_name ?? '—' }} @if($row->country_conflict)<span class="badge b-warn">Conflict</span>@endif</td><td>{{ $row->customer_account_id ?? '—' }}</td><td>{{ $row->customer_contact_id ?? '—' }}</td><td>{{ $row->customer_invoice_reference_id ?? '—' }}</td></tr>@endforeach</tbody></table></div>@if($rows->hasPages())<div style="padding:12px 16px">{{ $rows->links() }}</div>@endif</div>
<div class="card"><div class="card-h"><h2>Warnings and Errors</h2></div><div class="scroll-x"><table class="tbl"><thead><tr><th>Row</th><th>Severity</th><th>Field</th><th>Code</th><th>Message</th></tr></thead><tbody>@forelse($errors as $error)<tr><td>{{ $error->row_number ?? '—' }}</td><td><span class="badge {{ $error->severity === 'error' ? 'b-warn' : 'b-muted' }}">{{ $error->severity }}</span></td><td>{{ $error->field ?? '—' }}</td><td class="mono">{{ $error->code }}</td><td>{{ $error->message }}</td></tr>@empty<tr><td colspan="5"><div class="empty"><h3>No import warnings or errors</h3></div></td></tr>@endforelse</tbody></table></div></div>
@endsection
