<?php

namespace Database\Seeders\Suppliers;

use App\Models\Supplier\Supplier;
use Illuminate\Database\Seeder;

class SupplierSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $suppliers = [
            // Tier 1: Core Maker Ecosystem
            [
                'name' => 'Adafruit',
                'slug' => 'adafruit',
                'tier' => 'tier_1',
                'website' => 'https://www.adafruit.com',
                'api_endpoint' => 'https://api.adafruit.com',
                'description' => 'Arduino, ESP32, Raspberry Pi, Feather, STEM products',
                'logo_path' => 'suppliers/adafruit.png',
                'is_active' => true,
            ],
            [
                'name' => 'Waveshare',
                'slug' => 'waveshare',
                'tier' => 'tier_1',
                'website' => 'https://www.waveshare.com',
                'api_endpoint' => 'https://www.waveshare.com/api',
                'description' => 'Displays, e-paper, HATs, robotics, industrial modules',
                'logo_path' => 'suppliers/waveshare.png',
                'is_active' => true,
            ],
            [
                'name' => 'OKYSTAR',
                'slug' => 'okystar',
                'tier' => 'tier_1',
                'website' => 'https://www.okystar.com',
                'api_endpoint' => 'https://www.okystar.com/api',
                'description' => 'Arduino, sensors, modules, robotics',
                'logo_path' => 'suppliers/okystar.png',
                'is_active' => true,
            ],
            [
                'name' => 'SparkFun',
                'slug' => 'sparkfun',
                'tier' => 'tier_1',
                'website' => 'https://www.sparkfun.com',
                'api_endpoint' => 'https://api.sparkfun.com',
                'description' => 'Sensors, development boards, education',
                'logo_path' => 'suppliers/sparkfun.png',
                'is_active' => true,
            ],
            [
                'name' => 'Seeed Studio',
                'slug' => 'seeed-studio',
                'tier' => 'tier_1',
                'website' => 'https://www.seeedstudio.com',
                'api_endpoint' => 'https://api.seeedstudio.com',
                'description' => 'Grove ecosystem, IoT, AI hardware',
                'logo_path' => 'suppliers/seeed-studio.png',
                'is_active' => true,
            ],
            [
                'name' => 'DFRobot',
                'slug' => 'dfrobot',
                'tier' => 'tier_1',
                'website' => 'https://www.dfrobot.com',
                'api_endpoint' => 'https://api.dfrobot.com',
                'description' => 'Robotics, education, industrial sensors',
                'logo_path' => 'suppliers/dfrobot.png',
                'is_active' => true,
            ],
            
            // Tier 2: Industrial & Electronics
            [
                'name' => 'Arduino',
                'slug' => 'arduino',
                'tier' => 'tier_2',
                'website' => 'https://www.arduino.cc',
                'api_endpoint' => 'https://api.arduino.cc',
                'description' => 'Official Arduino boards and accessories',
                'logo_path' => 'suppliers/arduino.png',
                'is_active' => true,
            ],
            [
                'name' => 'Raspberry Pi',
                'slug' => 'raspberry-pi',
                'tier' => 'tier_2',
                'website' => 'https://www.raspberrypi.org',
                'api_endpoint' => 'https://api.raspberrypi.org',
                'description' => 'Raspberry Pi computers and accessories',
                'logo_path' => 'suppliers/raspberry-pi.png',
                'is_active' => true,
            ],
            [
                'name' => 'Espressif',
                'slug' => 'espressif',
                'tier' => 'tier_2',
                'website' => 'https://www.espressif.com',
                'api_endpoint' => 'https://api.espressif.com',
                'description' => 'ESP32, ESP8266 chips and modules',
                'logo_path' => 'suppliers/espressif.png',
                'is_active' => true,
            ],
            [
                'name' => 'STMicroelectronics',
                'slug' => 'stmicroelectronics',
                'tier' => 'tier_2',
                'website' => 'https://www.st.com',
                'api_endpoint' => 'https://api.st.com',
                'description' => 'Semiconductors and embedded solutions',
                'logo_path' => 'suppliers/stmicroelectronics.png',
                'is_active' => true,
            ],
            [
                'name' => 'Texas Instruments',
                'slug' => 'texas-instruments',
                'tier' => 'tier_2',
                'website' => 'https://www.ti.com',
                'api_endpoint' => 'https://api.ti.com',
                'description' => 'Analog and embedded processing',
                'logo_path' => 'suppliers/texas-instruments.png',
                'is_active' => true,
            ],
            [
                'name' => 'Analog Devices',
                'slug' => 'analog-devices',
                'tier' => 'tier_2',
                'website' => 'https://www.analog.com',
                'api_endpoint' => 'https://api.analog.com',
                'description' => 'High-performance analog ICs',
                'logo_path' => 'suppliers/analog-devices.png',
                'is_active' => true,
            ],
            [
                'name' => 'Microchip',
                'slug' => 'microchip',
                'tier' => 'tier_2',
                'website' => 'https://www.microchip.com',
                'api_endpoint' => 'https://api.microchip.com',
                'description' => 'Microcontrollers and analog semiconductors',
                'logo_path' => 'suppliers/microchip.png',
                'is_active' => true,
            ],
            [
                'name' => 'Nordic Semiconductor',
                'slug' => 'nordic-semiconductor',
                'tier' => 'tier_2',
                'website' => 'https://www.nordicsemi.com',
                'api_endpoint' => 'https://api.nordicsemi.com',
                'description' => 'Wireless connectivity solutions',
                'logo_path' => 'suppliers/nordic-semiconductor.png',
                'is_active' => true,
            ],
            [
                'name' => 'NXP',
                'slug' => 'nxp',
                'tier' => 'tier_2',
                'website' => 'https://www.nxp.com',
                'api_endpoint' => 'https://api.nxp.com',
                'description' => 'Secure connectivity solutions',
                'logo_path' => 'suppliers/nxp.png',
                'is_active' => true,
            ],
            [
                'name' => 'Quectel',
                'slug' => 'quectel',
                'tier' => 'tier_2',
                'website' => 'https://www.quectel.com',
                'api_endpoint' => 'https://api.quectel.com',
                'description' => 'IoT and GNSS modules',
                'logo_path' => 'suppliers/quectel.png',
                'is_active' => true,
            ],
            [
                'name' => 'SIMCom',
                'slug' => 'simcom',
                'tier' => 'tier_2',
                'website' => 'https://www.simcom.com',
                'api_endpoint' => 'https://api.simcom.com',
                'description' => 'Cellular and GNSS modules',
                'logo_path' => 'suppliers/simcom.png',
                'is_active' => true,
            ],
            [
                'name' => 'u-blox',
                'slug' => 'u-blox',
                'tier' => 'tier_2',
                'website' => 'https://www.u-blox.com',
                'api_endpoint' => 'https://api.u-blox.com',
                'description' => 'Positioning and wireless communication',
                'logo_path' => 'suppliers/u-blox.png',
                'is_active' => true,
            ],
            
            // Tier 3: Components & Connectors
            [
                'name' => 'Mean Well',
                'slug' => 'mean-well',
                'tier' => 'tier_3',
                'website' => 'https://www.meanwell.com',
                'api_endpoint' => 'https://api.meanwell.com',
                'description' => 'Power supplies',
                'logo_path' => 'suppliers/mean-well.png',
                'is_active' => true,
            ],
            [
                'name' => 'Hi-Link',
                'slug' => 'hi-link',
                'tier' => 'tier_3',
                'website' => 'https://www.hlktech.com',
                'api_endpoint' => 'https://api.hlktech.com',
                'description' => 'AC-DC power modules',
                'logo_path' => 'suppliers/hi-link.png',
                'is_active' => true,
            ],
            [
                'name' => 'JST',
                'slug' => 'jst',
                'tier' => 'tier_3',
                'website' => 'https://www.jst.com',
                'api_endpoint' => 'https://api.jst.com',
                'description' => 'Connectors and connection systems',
                'logo_path' => 'suppliers/jst.png',
                'is_active' => true,
            ],
            [
                'name' => 'Molex',
                'slug' => 'molex',
                'tier' => 'tier_3',
                'website' => 'https://www.molex.com',
                'api_endpoint' => 'https://api.molex.com',
                'description' => 'Electronic interconnection solutions',
                'logo_path' => 'suppliers/molex.png',
                'is_active' => true,
            ],
            [
                'name' => 'Omron',
                'slug' => 'omron',
                'tier' => 'tier_3',
                'website' => 'https://www.omron.com',
                'api_endpoint' => 'https://api.omron.com',
                'description' => 'Relays, switches, sensors',
                'logo_path' => 'suppliers/omron.png',
                'is_active' => true,
            ],
            [
                'name' => 'Panasonic',
                'slug' => 'panasonic',
                'tier' => 'tier_3',
                'website' => 'https://www.panasonic.com',
                'api_endpoint' => 'https://api.panasonic.com',
                'description' => 'Electronic components and batteries',
                'logo_path' => 'suppliers/panasonic.png',
                'is_active' => true,
            ],
            [
                'name' => 'Murata',
                'slug' => 'murata',
                'tier' => 'tier_3',
                'website' => 'https://www.murata.com',
                'api_endpoint' => 'https://api.murata.com',
                'description' => 'Ceramic capacitors, RF modules',
                'logo_path' => 'suppliers/murata.png',
                'is_active' => true,
            ],
            [
                'name' => 'Vishay',
                'slug' => 'vishay',
                'tier' => 'tier_3',
                'website' => 'https://www.vishay.com',
                'api_endpoint' => 'https://api.vishay.com',
                'description' => 'Discrete semiconductors and passive components',
                'logo_path' => 'suppliers/vishay.png',
                'is_active' => true,
            ],
            [
                'name' => 'Infineon',
                'slug' => 'infineon',
                'tier' => 'tier_3',
                'website' => 'https://www.infineon.com',
                'api_endpoint' => 'https://api.infineon.com',
                'description' => 'Power systems and IoT security',
                'logo_path' => 'suppliers/infineon.png',
                'is_active' => true,
            ],
            [
                'name' => 'ROHM',
                'slug' => 'rohm',
                'tier' => 'tier_3',
                'website' => 'https://www.rohm.com',
                'api_endpoint' => 'https://api.rohm.com',
                'description' => 'ICs, discrete devices, and modules',
                'logo_path' => 'suppliers/rohm.png',
                'is_active' => true,
            ],
        ];

        foreach ($suppliers as $supplier) {
            Supplier::updateOrCreate(
                ['slug' => $supplier['slug']],
                $supplier
            );
        }

        $this->command->info('✓ Seeded ' . count($suppliers) . ' suppliers across 3 tiers');
    }
}
