@extends('admin.layout')
@section('title','Inventory')
@section('crumb','Operations / Stock Ledger')
@section('page_actions')
<details class="modal"><summary class="btn btn-primary">Add Warehouse</summary><div class="modal-panel"><div class="modal-h"><h3>Add Warehouse</h3></div><form class="modal-b form-stack" method="post" action="/admin/inventory/warehouses">@csrf<div class="form-grid"><div class="field"><label>Name</label><input class="control" name="name" required></div><div class="field"><label>Code</label><input class="control" name="code"></div><div class="field"><label>Country</label><select class="control" name="country_id"><option value="">Global</option>@foreach($countries as $country)<option value="{{ $country->id }}">{{ $country->name }}</option>@endforeach</select></div><div class="field"><label>Phone</label><input class="control" name="contact_phone"></div></div><div class="field"><label>Address</label><input class="control" name="address_line1"></div><label><input type="checkbox" name="is_active" value="1" checked> Active</label><button class="btn btn-primary" type="submit">Save Warehouse</button></form></div></details>
<details class="modal"><summary class="btn btn-ghost">Adjust Stock</summary><div class="modal-panel"><div class="modal-h"><h3>Stock Adjustment</h3></div><form class="modal-b form-stack" method="post" action="/admin/inventory/stocks">@csrf<div class="form-grid"><div class="field"><label>Product</label><select class="control" name="product_id" required>@foreach($products as $p)<option value="{{ $p->id }}">{{ $p->name }} · {{ $p->sku }}</option>@endforeach</select></div><div class="field"><label>Warehouse</label><select class="control" name="warehouse_id" required>@foreach($warehouses as $w)<option value="{{ $w->id }}">{{ $w->name }}</option>@endforeach</select></div><div class="field"><label>Available</label><input class="control" type="number" name="quantity_available" required></div><div class="field"><label>Reorder point</label><input class="control" type="number" name="reorder_point" value="5"></div></div><div class="field"><label>Note</label><textarea class="control" name="notes"></textarea></div><button class="btn btn-primary" type="submit">Post Adjustment</button></form></div></details>
<details class="modal"><summary class="btn btn-ghost">Transfer</summary><div class="modal-panel"><div class="modal-h"><h3>Transfer Warehouse Stock</h3></div><form class="modal-b form-stack" method="post" action="/admin/inventory/transfers">@csrf<div class="form-grid"><div class="field"><label>Product</label><select class="control" name="product_id" required>@foreach($products as $p)<option value="{{ $p->id }}">{{ $p->name }} · {{ $p->sku }}</option>@endforeach</select></div><div class="field"><label>From warehouse</label><select class="control" name="from_warehouse_id" required>@foreach($warehouses as $w)<option value="{{ $w->id }}">{{ $w->name }}</option>@endforeach</select></div><div class="field"><label>To warehouse</label><select class="control" name="to_warehouse_id" required>@foreach($warehouses as $w)<option value="{{ $w->id }}">{{ $w->name }}</option>@endforeach</select></div><div class="field"><label>Quantity</label><input class="control" type="number" min="1" name="quantity" required></div></div><textarea class="control" name="notes" placeholder="Transfer note"></textarea><button class="btn btn-primary" type="submit">Post Transfer</button></form></div></details>
<details class="modal"><summary class="btn btn-ghost">Reserve</summary><div class="modal-panel"><div class="modal-h"><h3>Reserve Stock</h3></div><form class="modal-b form-stack" method="post" action="/admin/inventory/reservations">@csrf<div class="form-grid"><div class="field"><label>Product</label><select class="control" name="product_id" required>@foreach($products as $p)<option value="{{ $p->id }}">{{ $p->name }} · {{ $p->sku }}</option>@endforeach</select></div><div class="field"><label>Warehouse</label><select class="control" name="warehouse_id" required>@foreach($warehouses as $w)<option value="{{ $w->id }}">{{ $w->name }}</option>@endforeach</select></div><div class="field"><label>Quantity</label><input class="control" type="number" min="1" name="quantity" required></div><div class="field"><label>Reference type</label><input class="control" name="reference_type" value="admin_hold"></div></div><textarea class="control" name="notes" placeholder="Reservation note"></textarea><button class="btn btn-primary" type="submit">Reserve Stock</button></form></div></details>
<form method="post" action="/admin/inventory/low-stock/generate">@csrf<button class="btn btn-ghost" type="submit">Refresh Alerts</button></form>
@endsection
@section('content')
<div class="grid kpis"><div class="kpi"><div class="t">Warehouses</div><div class="v tnum">{{ number_format($stats['warehouses']) }}</div><div class="s">locations</div></div><div class="kpi"><div class="t">Stock Rows</div><div class="v tnum">{{ number_format($stats['stockRows']) }}</div><div class="s">product locations</div></div><div class="kpi"><div class="t">Available</div><div class="v tnum">{{ number_format($stats['availableUnits']) }}</div><div class="s">units</div></div><div class="kpi"><div class="t">Low Stock</div><div class="v tnum">{{ number_format($stats['lowStockRows']) }}</div><div class="s">alerts</div></div></div>
<div class="grid split"><section class="card"><div class="card-h"><h2>Stock Rows</h2><span class="badge b-info">warehouse/product filters ready</span></div><div class="scroll-x"><table class="tbl"><thead><tr><th>Product</th><th>Warehouse</th><th>Available</th><th>Reserved</th><th>Reorder</th></tr></thead><tbody>@forelse($stocks as $s)<tr><td>{{ $s->product_name ?? ('#'.$s->product_id) }}<div class="sub mono">{{ $s->product_sku ?? $s->sku }}</div></td><td>{{ $s->warehouse_name ?? ('#'.$s->warehouse_id) }}</td><td class="tnum">{{ $s->quantity_available }}</td><td class="tnum">{{ $s->quantity_reserved }}</td><td class="tnum">{{ $s->reorder_point }}</td></tr>@empty<tr><td colspan="5"><div class="empty"><h3>No stock rows</h3></div></td></tr>@endforelse</tbody></table></div></section><section class="card"><div class="card-h"><h2>Movement History</h2><span class="badge b-info">drawer-ready</span></div><div class="scroll-x"><table class="tbl"><thead><tr><th>Type</th><th>Product</th><th>Qty</th><th>After</th></tr></thead><tbody>@forelse($movements as $m)<tr><td><span class="badge b-muted">{{ $m->movement_type }}</span></td><td>#{{ $m->product_id }}</td><td class="tnum">{{ $m->quantity_change }}</td><td class="tnum">{{ $m->quantity_after }}</td></tr>@empty<tr><td colspan="4"><div class="empty"><h3>No movements</h3></div></td></tr>@endforelse</tbody></table></div></section></div>
<div class="grid split stack-gap">
    <section class="card"><div class="card-h"><div><h2>Reservations</h2><div class="sub">{{ number_format($stats['activeReservations']) }} active</div></div></div><div class="scroll-x"><table class="tbl"><thead><tr><th>Product</th><th>Warehouse</th><th>Qty</th><th>Status</th><th>Action</th></tr></thead><tbody>@forelse($reservations as $reservation)<tr><td>{{ $reservation->product_name ?? ('#'.$reservation->product_id) }}<div class="sub mono">{{ $reservation->product_sku }}</div></td><td>{{ $reservation->warehouse_name ?? ('#'.$reservation->warehouse_id) }}</td><td class="tnum">{{ $reservation->quantity }}</td><td><span class="badge {{ $reservation->status === 'active' ? 'b-ok' : 'b-muted' }}">{{ $reservation->status }}</span></td><td>@if($reservation->status === 'active')<form method="post" action="/admin/inventory/reservations/{{ $reservation->id }}/release">@csrf<button class="btn btn-ghost" type="submit">Release</button></form>@endif</td></tr>@empty<tr><td colspan="5"><div class="empty"><h3>No reservations</h3></div></td></tr>@endforelse</tbody></table></div></section>
    <section class="card"><div class="card-h"><div><h2>Low-stock Alerts</h2><div class="sub">{{ number_format($stats['activeLowStockAlerts']) }} active</div></div></div><div class="scroll-x"><table class="tbl"><thead><tr><th>Product</th><th>Warehouse</th><th>Available</th><th>Status</th><th>Action</th></tr></thead><tbody>@forelse($lowStockAlerts as $alert)<tr><td>{{ $alert->product_name ?? ('#'.$alert->product_id) }}<div class="sub mono">{{ $alert->product_sku }}</div></td><td>{{ $alert->warehouse_name ?? ('#'.$alert->warehouse_id) }}</td><td class="tnum">{{ $alert->available_quantity }} / {{ $alert->threshold }}</td><td><span class="badge {{ in_array($alert->status, ['open','active']) ? 'b-warn' : 'b-muted' }}">{{ $alert->status }}</span></td><td><form method="post" action="/admin/inventory/low-stock/{{ $alert->id }}/action">@csrf<select class="control" name="action"><option value="acknowledge">Acknowledge</option><option value="reorder_queued">Queue reorder</option><option value="resolve">Resolve</option><option value="ignore">Ignore</option></select><button class="btn btn-ghost" type="submit">Apply</button></form></td></tr>@empty<tr><td colspan="5"><div class="empty"><h3>No low-stock alerts</h3></div></td></tr>@endforelse</tbody></table></div></section>
</div>
@endsection
