@extends('admin.layout')
@section('title','Inventory')
@section('crumb','Operations / Stock Ledger')
@section('page_actions')
<details class="modal"><summary class="btn btn-primary">Add Warehouse</summary><div class="modal-panel"><div class="modal-h"><h3>Add Warehouse</h3></div><form class="modal-b form-stack" method="post" action="/admin/inventory/warehouses">@csrf<div class="form-grid"><div class="field"><label>Name</label><input class="control" name="name" required></div><div class="field"><label>Code</label><input class="control" name="code"></div><div class="field"><label>Marketplace</label><select class="control" name="marketplace_id"><option value="">Unassigned / global</option>@foreach($marketplaces as $marketplace)<option value="{{ $marketplace->id }}">{{ $marketplace->name }} · {{ $marketplace->code }}</option>@endforeach</select></div><div class="field"><label>Country</label><select class="control" name="country_id"><option value="">Use marketplace country</option>@foreach($countries as $country)<option value="{{ $country->id }}">{{ $country->name }}</option>@endforeach</select></div><div class="field"><label>Phone</label><input class="control" name="contact_phone"></div></div><div class="field"><label>Address</label><input class="control" name="address_line1"></div><label><input type="checkbox" name="is_active" value="1" checked> Active</label><button class="btn btn-primary" type="submit">Save Warehouse</button></form></div></details>
<details class="modal"><summary class="btn btn-ghost">Adjust Stock</summary><div class="modal-panel"><div class="modal-h"><h3>Stock Adjustment</h3></div><form class="modal-b form-stack" method="post" action="/admin/inventory/stocks">@csrf<div class="form-grid"><div class="field"><label>Product</label><select class="control" name="product_id" required>@foreach($products as $p)<option value="{{ $p->id }}">{{ $p->name }} · {{ $p->sku }}</option>@endforeach</select></div><div class="field"><label>Warehouse</label><select class="control" name="warehouse_id" required>@foreach($warehouses as $w)<option value="{{ $w->id }}">{{ $w->name }}</option>@endforeach</select></div><div class="field"><label>Available</label><input class="control" type="number" name="quantity_available" required></div><div class="field"><label>Reorder point</label><input class="control" type="number" name="reorder_point" value="5"></div></div><div class="field"><label>Note</label><textarea class="control" name="notes"></textarea></div><button class="btn btn-primary" type="submit">Post Adjustment</button></form></div></details>
@endsection
@section('content')
<div class="grid kpis"><div class="kpi"><div class="t">Warehouses</div><div class="v tnum">{{ number_format($stats['warehouses']) }}</div><div class="s">locations</div></div><div class="kpi"><div class="t">Stock Rows</div><div class="v tnum">{{ number_format($stats['stockRows']) }}</div><div class="s">product locations</div></div><div class="kpi"><div class="t">Available</div><div class="v tnum">{{ number_format($stats['availableUnits']) }}</div><div class="s">units</div></div><div class="kpi"><div class="t">Low Stock</div><div class="v tnum">{{ number_format($stats['lowStockRows']) }}</div><div class="s">alerts</div></div></div>
<div class="grid split"><section class="card"><div class="card-h"><h2>Stock Rows</h2><span class="badge b-info">warehouse/product filters ready</span></div><div class="scroll-x"><table class="tbl"><thead><tr><th>Product</th><th>Warehouse</th><th>Available</th><th>Reserved</th><th>Reorder</th></tr></thead><tbody>@forelse($stocks as $s)<tr><td>{{ $s->product_name ?? ('#'.$s->product_id) }}<div class="sub mono">{{ $s->product_sku ?? $s->sku }}</div></td><td>{{ $s->warehouse_name ?? ('#'.$s->warehouse_id) }}</td><td class="tnum">{{ $s->quantity_available }}</td><td class="tnum">{{ $s->quantity_reserved }}</td><td class="tnum">{{ $s->reorder_point }}</td></tr>@empty<tr><td colspan="5"><div class="empty"><h3>No stock rows</h3></div></td></tr>@endforelse</tbody></table></div></section><section class="card"><div class="card-h"><h2>Movement History</h2><span class="badge b-info">drawer-ready</span></div><div class="scroll-x"><table class="tbl"><thead><tr><th>Type</th><th>Product</th><th>Qty</th><th>After</th></tr></thead><tbody>@forelse($movements as $m)<tr><td><span class="badge b-muted">{{ $m->movement_type }}</span></td><td>#{{ $m->product_id }}</td><td class="tnum">{{ $m->quantity_change }}</td><td class="tnum">{{ $m->quantity_after }}</td></tr>@empty<tr><td colspan="4"><div class="empty"><h3>No movements</h3></div></td></tr>@endforelse</tbody></table></div></section></div>
<div class="note stack-gap">Reserve stock, transfers, low-stock alert workflow, country/product filters and movement detail drawers are staged as UI/operation placeholders; warehouse creation and stock adjustment are active.</div>
@endsection
