@extends('admin.layout')
@section('title','LMS')
@section('crumb','Learning / Course Operations')
@section('page_actions')
<details class="modal"><summary class="btn btn-primary">Create Course</summary><div class="modal-panel"><div class="modal-h"><h3>Create Course</h3><span class="badge b-info">publish-ready</span></div><form class="modal-b form-stack" method="post" action="/admin/lms/courses">@csrf<div class="form-grid"><div class="field"><label>Title</label><input class="control" name="title" required></div><div class="field"><label>Slug</label><input class="control mono" name="slug"></div><div class="field"><label>Category</label><select class="control" name="lms_course_category_id"><option value="">None</option>@foreach($categories as $cat)<option value="{{ $cat->id }}">{{ $cat->name }}</option>@endforeach</select></div><div class="field"><label>Status</label><select class="control" name="status"><option>draft</option><option>published</option></select></div><div class="field"><label>Level</label><select class="control" name="level"><option>beginner</option><option>intermediate</option><option>advanced</option></select></div><div class="field"><label>Minutes</label><input class="control" type="number" name="estimated_minutes"></div></div><div class="field"><label>Subtitle</label><input class="control" name="subtitle"></div><div class="field"><label>Description</label><textarea class="control" name="description"></textarea></div><div class="form-grid"><div class="field"><label>SEO title</label><input class="control" name="seo_title"></div><div class="field"><label>SEO description</label><input class="control" name="seo_description"></div></div><button class="btn btn-primary" type="submit">Save Course</button></form></div></details>
<details class="modal"><summary class="btn btn-ghost">Add Lesson</summary><div class="modal-panel"><div class="modal-h"><h3>Add Lesson/Tutorial</h3><span class="badge b-info">video/file ready</span></div><form class="modal-b form-stack" method="post" action="/admin/lms/lessons">@csrf<div class="form-grid"><div class="field"><label>Course</label><select class="control" name="lms_course_id"><option value="">None</option>@foreach($courses as $c)<option value="{{ $c->id }}">{{ $c->title }}</option>@endforeach</select></div><div class="field"><label>Module</label><select class="control" name="lms_module_id"><option value="">None</option>@foreach($modules as $m)<option value="{{ $m->id }}">{{ $m->title }}</option>@endforeach</select></div><div class="field"><label>Title</label><input class="control" name="title" required></div><div class="field"><label>Status</label><select class="control" name="status"><option>draft</option><option>published</option></select></div></div><div class="field"><label>Video URL</label><input class="control" name="video_url"></div><div class="field"><label>Summary</label><textarea class="control" name="summary"></textarea></div><div class="field"><label>Content</label><textarea class="control" name="content"></textarea></div><button class="btn btn-primary" type="submit">Save Lesson</button></form></div></details>
@endsection
@section('content')
<div class="grid kpis"><div class="kpi"><div class="t">Courses</div><div class="v tnum">{{ number_format($stats['courses']) }}</div><div class="s">{{ number_format($stats['publishedCourses']) }} published</div></div><div class="kpi"><div class="t">Projects</div><div class="v tnum">{{ number_format($stats['projects']) }}</div><div class="s">tutorials</div></div><div class="kpi"><div class="t">Lessons</div><div class="v tnum">{{ number_format($stats['lessons']) }}</div><div class="s">learning units</div></div><div class="kpi"><div class="t">Certificates</div><div class="v tnum">{{ number_format($stats['certificates']) }}</div><div class="s">issued</div></div></div>
<div class="grid split"><section class="card"><div class="card-h"><h2>Courses</h2><span class="badge b-info">CRUD</span></div><div class="scroll-x"><table class="tbl"><thead><tr><th>Title</th><th>Level</th><th>Status</th><th>Actions</th></tr></thead><tbody>@forelse($courses as $c)<tr><td><strong>{{ $c->title }}</strong><div class="sub mono">{{ $c->slug }}</div></td><td>{{ $c->level }}</td><td><span class="badge {{ $c->status==='published'?'b-ok':'b-muted' }}">{{ $c->status }}</span></td><td><form method="post" action="/admin/lms/courses/{{ $c->id }}/toggle">@csrf<button class="btn btn-ghost" type="submit">{{ $c->status==='published'?'Unpublish':'Publish' }}</button></form></td></tr>@empty<tr><td colspan="4"><div class="empty"><h3>No courses yet</h3></div></td></tr>@endforelse</tbody></table></div></section><section class="card"><div class="card-h"><h2>Lessons</h2><span class="badge b-info">latest</span></div><div class="scroll-x"><table class="tbl"><thead><tr><th>Lesson</th><th>Type</th><th>Status</th></tr></thead><tbody>@forelse($lessons as $l)<tr><td><strong>{{ $l->title }}</strong><div class="sub">{{ $l->summary }}</div></td><td>{{ $l->type }}</td><td><span class="badge b-muted">{{ $l->status }}</span></td></tr>@empty<tr><td colspan="3"><div class="empty"><h3>No lessons</h3></div></td></tr>@endforelse</tbody></table></div></section></div>
<section class="card stack-gap"><div class="card-h"><h2>Student Progress & Certificates</h2><span class="badge b-warn">AI tutor placeholder</span></div><div class="scroll-x"><table class="tbl"><thead><tr><th>Learner</th><th>Course</th><th>Progress</th><th>Status</th></tr></thead><tbody>@forelse($enrollments as $e)<tr><td class="mono">{{ $e->email ?? ('user#'.$e->user_id) }}</td><td>#{{ $e->lms_course_id }}</td><td class="tnum">{{ number_format((float)$e->progress_percent,2) }}%</td><td><span class="badge b-muted">{{ $e->status }}</span></td></tr>@empty<tr><td colspan="4"><div class="empty"><h3>No enrollments yet</h3></div></td></tr>@endforelse</tbody></table></div></section>
@endsection
