<?php

namespace Database\Seeders;

use App\Models\Education\EducationProject;
use App\Models\Education\BomLine;
use App\Models\Education\CodeFile;
use App\Models\Education\SensorKnowledge;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class EducationProjectSeeder extends Seeder
{
    public function run(): void
    {
        $this->seedSensors();
        $this->seedProjects();
    }

    private function seedSensors(): void
    {
        $sensors = [
            [
                'sensor_type' => 'dht22',
                'display_name' => 'DHT22 Temperature & Humidity Sensor',
                'function_description' => 'Measures temperature and humidity. Digital output with built-in ADC.',
                'input_output_type' => 'Digital',
                'voltage_range' => '3.3-6V',
                'current_consumption' => '1.5mA',
                'interface' => 'One-Wire',
                'range' => '-40°C to 80°C, 0-100% RH',
                'accuracy' => '±0.5°C, ±2% RH',
                'resolution' => '0.1°C, 0.1% RH',
                'response_time' => '2s',
                'operating_conditions' => '-40°C to 80°C, 0-100% RH',
                'calibration_notes' => 'Factory calibrated. No user calibration required for most applications.',
                'compatible_controllers' => ['Arduino', 'ESP32', 'Raspberry Pi', 'STM32'],
                'compatible_libraries' => ['DHT', 'DHT sensor library', 'Adafruit Unified Sensor'],
                'applications' => ['Weather stations', 'Home automation', 'HVAC monitoring', 'Agriculture'],
                'limitations' => ['Maximum 1 reading per 2 seconds', 'Not suitable for condensing environments'],
                'safety_notes' => 'Handle with care. Avoid touching the sensing element.',
            ],
            [
                'sensor_type' => 'bmp280',
                'display_name' => 'BMP280 Barometric Pressure Sensor',
                'function_description' => 'Measures barometric pressure and temperature. High precision digital sensor.',
                'input_output_type' => 'Digital',
                'voltage_range' => '1.71-3.6V',
                'current_consumption' => '2.7µA',
                'interface' => 'I2C, SPI',
                'range' => '300-1100 hPa, -40°C to 85°C',
                'accuracy' => '±1 hPa, ±1°C',
                'resolution' => '0.01 hPa, 0.01°C',
                'response_time' => '1ms',
                'operating_conditions' => '-40°C to 85°C, 0-100% RH',
                'calibration_notes' => 'Factory calibrated with individual compensation coefficients.',
                'compatible_controllers' => ['Arduino', 'ESP32', 'Raspberry Pi', 'STM32', 'Micro:bit'],
                'compatible_libraries' => ['Adafruit BMP280', 'BME280', 'SparkFun BMP280'],
                'applications' => ['Weather stations', 'Altitude measurement', 'Indoor navigation', 'GPS enhancement'],
                'limitations' => ['Not suitable for liquid level measurement'],
                'safety_notes' => 'Standard ESD precautions.',
            ],
            [
                'sensor_type' => 'hc_sr04',
                'display_name' => 'HC-SR04 Ultrasonic Distance Sensor',
                'function_description' => 'Measures distance using ultrasonic waves. Non-contact distance measurement.',
                'input_output_type' => 'Digital',
                'voltage_range' => '5V',
                'current_consumption' => '15mA',
                'interface' => 'Trigger/Echo',
                'range' => '2cm - 400cm',
                'accuracy' => '±3mm',
                'resolution' => '3mm',
                'response_time' => '60ms',
                'operating_conditions' => '-15°C to 70°C',
                'calibration_notes' => 'No calibration required. Temperature compensation may improve accuracy.',
                'compatible_controllers' => ['Arduino', 'ESP32', 'Raspberry Pi', 'STM32', 'Micro:bit'],
                'compatible_libraries' => ['NewPing', 'HCSR04'],
                'applications' => ['Robot obstacle avoidance', 'Level measurement', 'Parking sensors', 'Security systems'],
                'limitations' => ['Minimum 2cm distance', 'Affected by soft/absorbing surfaces', 'Narrow beam angle'],
                'safety_notes' => 'Low power. Safe for all applications.',
            ],
            [
                'sensor_type' => 'soil_moisture_analog',
                'display_name' => 'Soil Moisture Sensor (Analog)',
                'function_description' => 'Measures soil moisture content using capacitive sensing.',
                'input_output_type' => 'Analog + Digital',
                'voltage_range' => '3.3-5V',
                'current_consumption' => '20mA',
                'interface' => 'Analog',
                'range' => '0-100% (relative)',
                'accuracy' => '±5%',
                'resolution' => '1%',
                'response_time' => '1s',
                'operating_conditions' => '-40°C to 80°C',
                'calibration_notes' => 'Requires calibration in dry and wet soil conditions.',
                'compatible_controllers' => ['Arduino', 'ESP32', 'Raspberry Pi'],
                'compatible_libraries' => ['AnalogRead'],
                'applications' => ['Smart irrigation', 'Agriculture monitoring', 'Plant care systems'],
                'limitations' => ['Corrosion over time if not properly coated', 'Requires calibration'],
                'safety_notes' => 'Use waterproof version for outdoor installations.',
            ],
            [
                'sensor_type' => 'ir_obstacle',
                'display_name' => 'IR Obstacle Avoidance Sensor',
                'function_description' => 'Detects obstacles using infrared reflection. Digital output.',
                'input_output_type' => 'Digital + Analog',
                'voltage_range' => '3.3-5V',
                'current_consumption' => '20mA',
                'interface' => 'Digital (DO) + Analog (AO)',
                'range' => '2-30cm',
                'accuracy' => 'Distance-dependent',
                'resolution' => 'Proximity only',
                'response_time' => '1ms',
                'operating_conditions' => '-10°C to 60°C',
                'calibration_notes' => 'Adjust potentiometer for detection distance threshold.',
                'compatible_controllers' => ['Arduino', 'ESP32', 'Raspberry Pi', 'Micro:bit'],
                'compatible_libraries' => ['AnalogRead', 'DigitalRead'],
                'applications' => ['Robot obstacle avoidance', 'Line following', 'Edge detection'],
                'limitations' => ['Affected by ambient light', 'Surface color affects range', 'Narrow detection angle'],
                'safety_notes' => 'IR LED is invisible but safe at these power levels.',
            ],
            [
                'sensor_type' => 'mpu6050',
                'display_name' => 'MPU6050 6-Axis Accelerometer & Gyroscope',
                'function_description' => 'Measures acceleration and angular velocity in 3 axes.',
                'input_output_type' => 'Digital',
                'voltage_range' => '2.375-3.46V',
                'current_consumption' => '3.9mA',
                'interface' => 'I2C',
                'range' => '±2g/±4g/±8g/±16g (accel), ±250/500/1000/2000°/s (gyro)',
                'accuracy' => '±2g (accel), ±1% (gyro)',
                'resolution' => '16-bit',
                'response_time' => '1kHz sampling',
                'operating_conditions' => '-40°C to 85°C',
                'calibration_notes' => 'Factory calibrated. Software calibration recommended for precision.',
                'compatible_controllers' => ['Arduino', 'ESP32', 'Raspberry Pi', 'STM32'],
                'compatible_libraries' => ['Wire', 'Adafruit MPU6050', 'MPU6050_tockn'],
                'applications' => ['Robotics', 'Drone stabilization', 'Motion tracking', 'Gaming controllers'],
                'limitations' => ['Temperature drift', 'Requires calibration for precise measurements'],
                'safety_notes' => 'Standard ESD precautions.',
            ],
            [
                'sensor_type' => 'photoresistor',
                'display_name' => 'Photoresistor (LDR)',
                'function_description' => 'Light-dependent resistor. Resistance decreases with light intensity.',
                'input_output_type' => 'Analog',
                'voltage_range' => '3.3-5V (with voltage divider)',
                'current_consumption' => '1mA',
                'interface' => 'Analog',
                'range' => '1 lux to 100,000 lux',
                'accuracy' => 'Relative only',
                'resolution' => 'Analog',
                'response_time' => '10-20ms',
                'operating_conditions' => '-30°C to 70°C',
                'calibration_notes' => 'Requires voltage divider circuit. Calibration varies by lighting conditions.',
                'compatible_controllers' => ['Arduino', 'ESP32', 'Raspberry Pi', 'Micro:bit'],
                'compatible_libraries' => ['AnalogRead'],
                'applications' => ['Street light control', 'Security systems', 'Solar tracking', 'Display brightness'],
                'limitations' => ['Non-linear response', 'Temperature sensitive', 'Slow response to rapid changes'],
                'safety_notes' => 'Standard electronic component handling.',
            ],
            [
                'sensor_type' => 'rain_sensor',
                'display_name' => 'Rain Detection Sensor',
                'function_description' => 'Detects rain or water presence on the sensor surface.',
                'input_output_type' => 'Digital + Analog',
                'voltage_range' => '3.3-5V',
                'current_consumption' => '15mA',
                'interface' => 'Digital + Analog',
                'range' => 'Rain detection (binary)',
                'accuracy' => 'Binary (rain/no rain)',
                'resolution' => 'Binary',
                'response_time' => '<1s',
                'operating_conditions' => '-10°C to 60°C',
                'calibration_notes' => 'Adjust sensitivity potentiometer for detection threshold.',
                'compatible_controllers' => ['Arduino', 'ESP32', 'Raspberry Pi'],
                'compatible_libraries' => ['AnalogRead', 'DigitalRead'],
                'applications' => ['Weather stations', 'Automatic window closers', 'Agriculture'],
                'limitations' => ['Sensor surface degrades over time', 'Requires periodic cleaning'],
                'safety_notes' => 'Low voltage. Safe for outdoor use with proper enclosure.',
            ],
            [
                'sensor_type' => 'flame_sensor',
                'display_name' => 'Flame Detection Sensor',
                'function_description' => 'Detects infrared light from flames. Digital and analog output.',
                'input_output_type' => 'Digital + Analog',
                'voltage_range' => '3.3-5V',
                'current_consumption' => '15mA',
                'interface' => 'Digital + Analog',
                'range' => '1 meter detection distance',
                'accuracy' => 'Direction-dependent',
                'resolution' => 'Binary (flame/no flame)',
                'response_time' => '<1s',
                'operating_conditions' => '-25°C to 85°C',
                'calibration_notes' => 'Adjust sensitivity potentiometer. Test in safe environment.',
                'compatible_controllers' => ['Arduino', 'ESP32', 'Raspberry Pi'],
                'compatible_libraries' => ['AnalogRead', 'DigitalRead'],
                'applications' => ['Fire detection', 'Safety systems', 'Robot fire-fighting'],
                'limitations' => ['Affected by ambient IR sources', 'Limited detection angle', 'Short range'],
                'safety_notes' => 'TEST IN SAFE ENVIRONMENT ONLY. Not a replacement for certified fire detectors.',
            ],
            [
                'sensor_type' => 'mq2_gas',
                'display_name' => 'MQ-2 Gas Sensor',
                'function_description' => 'Detects combustible gases, smoke, and LPG. Analog and digital output.',
                'input_output_type' => 'Analog + Digital',
                'voltage_range' => '5V',
                'current_consumption' => '150mA',
                'interface' => 'Analog + Digital',
                'range' => '200-10000ppm (gas dependent)',
                'accuracy' => 'Relative (requires calibration)',
                'resolution' => 'Analog',
                'response_time' => '<1s',
                'operating_conditions' => '-10°C to 50°C',
                'calibration_notes' => 'Requires 24-48 hour burn-in period. Calibrate in clean air first.',
                'compatible_controllers' => ['Arduino', 'ESP32', 'Raspberry Pi'],
                'compatible_libraries' => ['MQ2', 'AnalogRead'],
                'applications' => ['Gas leak detection', 'Air quality monitoring', 'Fire detection', 'Industrial safety'],
                'limitations' => ['Requires burn-in time', 'Cross-sensitivity to multiple gases', 'Temperature dependent'],
                'safety_notes' => 'Contains heated element. Do not expose to flammable gases during calibration. Use in ventilated area.',
            ],
            [
                'sensor_type' => 'max30102',
                'display_name' => 'MAX30102 Pulse Oximeter & Heart Rate Sensor',
                'function_description' => 'Measures heart rate and blood oxygen saturation using photoplethysmography.',
                'input_output_type' => 'Digital',
                'voltage_range' => '1.8-3.3V',
                'current_consumption' => '1.2mA',
                'interface' => 'I2C',
                'range' => 'Heart rate: 30-180bpm, SpO2: 0-100%',
                'accuracy' => '±2bpm (heart rate), ±2% (SpO2)',
                'resolution' => '18-bit ADC',
                'response_time' => '100ms',
                'operating_conditions' => '-40°C to 85°C',
                'calibration_notes' => 'Factory calibrated. Finger placement affects readings.',
                'compatible_controllers' => ['Arduino', 'ESP32', 'Raspberry Pi'],
                'compatible_libraries' => ['MAX30105', 'PulseSensor'],
                'applications' => ['Health monitoring', 'Wearables', 'Fitness tracking', 'Medical devices'],
                'limitations' => ['Requires skin contact', 'Affected by motion artifacts', 'Not FDA cleared'],
                'safety_notes' => 'For educational and prototyping purposes only. Not a medical device.',
            ],
            [
                'sensor_type' => 'ds18b20',
                'display_name' => 'DS18B20 Digital Temperature Sensor',
                'function_description' => 'High-precision digital temperature sensor with unique 64-bit address.',
                'input_output_type' => 'Digital',
                'voltage_range' => '3.0-5.5V',
                'current_consumption' => '1mA',
                'interface' => 'One-Wire',
                'range' => '-55°C to +125°C',
                'accuracy' => '±0.5°C (-10°C to +85°C)',
                'resolution' => '9-12 bit (configurable)',
                'response_time' => '750ms (12-bit)',
                'operating_conditions' => '-55°C to +125°C',
                'calibration_notes' => 'Factory calibrated. Individual calibration available in waterproof version.',
                'compatible_controllers' => ['Arduino', 'ESP32', 'Raspberry Pi', 'STM32'],
                'compatible_libraries' => ['OneWire', 'DallasTemperature', 'DallasTemperature library'],
                'applications' => ['Temperature monitoring', 'HVAC control', 'Weather stations', 'Industrial sensing'],
                'limitations' => ['Maximum 12 sensors per bus without parasite power', '750ms conversion at 12-bit'],
                'safety_notes' => 'Waterproof version suitable for immersion. Standard ESD precautions.',
            ],
            [
                'sensor_type' => 'hcsr501',
                'display_name' => 'HC-SR501 PIR Motion Sensor',
                'function_description' => 'Passive infrared motion detector with adjustable sensitivity and delay.',
                'input_output_type' => 'Digital',
                'voltage_range' => '4.5-20V',
                'current_consumption' => '65mA',
                'interface' => 'Digital',
                'range' => '3-7 meters (adjustable)',
                'accuracy' => 'Motion detection (binary)',
                'resolution' => 'Binary (motion/no motion)',
                'response_time' => '<1s',
                'operating_conditions' => '-15°C to 70°C',
                'calibration_notes' => 'Adjust sensitivity and time delay potentiometers. Optimal at 3-5m distance.',
                'compatible_controllers' => ['Arduino', 'ESP32', 'Raspberry Pi', 'Micro:bit'],
                'compatible_libraries' => ['DigitalRead'],
                'applications' => ['Security systems', 'Automatic lighting', 'Motion-activated devices', 'Smart home'],
                'limitations' => ['Affected by temperature changes', 'Limited detection angle (~120°)', 'False triggers near heat sources'],
                'safety_notes' => 'Low power. Suitable for battery operation.',
            ],
            [
                'sensor_type' => 'sh1106_oled',
                'display_name' => 'SH1106 1.3" OLED Display',
                'function_description' => '128x64 monochrome OLED display for text and graphics.',
                'input_output_type' => 'Digital (Output)',
                'voltage_range' => '3.3-5V',
                'current_consumption' => '20mA',
                'interface' => 'I2C, SPI',
                'range' => 'N/A (display)',
                'accuracy' => 'N/A',
                'resolution' => '128x64 pixels',
                'response_time' => 'N/A',
                'operating_conditions' => '-20°C to 70°C',
                'calibration_notes' => 'No calibration required.',
                'compatible_controllers' => ['Arduino', 'ESP32', 'Raspberry Pi', 'STM32', 'Micro:bit'],
                'compatible_libraries' => ['Adafruit SH1106', 'U8g2', 'SSD1306Ascii'],
                'applications' => ['Data display', 'User interfaces', 'Status monitors', 'Debug output'],
                'limitations' => ['Small text size', 'Limited viewing angle', 'No backlight'],
                'safety_notes'=> 'Standard electronic component handling.',
            ],
            [
                'sensor_type' => 'rc522_rfid',
                'display_name' => 'RC522 RFID Reader Module',
                'function_description' => '13.56MHz RFID reader/writer for MIFARE cards and tags.',
                'input_output_type' => 'Digital',
                'voltage_range' => '3.3V',
                'current_consumption' => '130mA',
                'interface' => 'SPI',
                'range' => '0-5cm (card dependent)',
                'accuracy' => 'Binary (read/no read)',
                'resolution' => 'N/A',
                'response_time' => '<100ms',
                'operating_conditions' => '-20°C to 85°C',
                'calibration_notes' => 'No calibration required. Antenna tuning may improve range.',
                'compatible_controllers' => ['Arduino', 'ESP32', 'Raspberry Pi', 'STM32'],
                'compatible_libraries' => ['MFRC522', 'RFID'],
                'applications' => ['Access control', 'Attendance systems', 'Payment systems', 'Asset tracking'],
                'limitations' => ['Limited range', 'Only MIFARE cards', '3.3V logic only'],
                'safety_notes'=> 'Safe for all applications. Standard ESD precautions.',
            ],
            [
                'sensor_type' => 'gps_neo6m',
                'display_name'=> 'NEO-6M GPS Module',
                'function_description' => 'GPS receiver with UART interface. Provides latitude, longitude, altitude, speed, and time.',
                'input_output_type' => 'Digital (UART)',
                'voltage_range' => '3.3-5V',
                'current_consumption' => '45mA',
                'interface' => 'UART (9600 baud)',
                'range' => 'Global (GPS coverage)',
                'accuracy' => '2.5m CEP',
                'resolution' => '0.000001° latitude/longitude',
                'response_time' => '1Hz update rate',
                'operating_conditions' => '-40°C to 85°C',
                'calibration_notes' => 'Cold start may take 2-5 minutes for first fix. Antenna placement affects signal.',
                'compatible_controllers' => ['Arduino', 'ESP32', 'Raspberry Pi', 'STM32'],
                'compatible_libraries' => ['TinyGPS++', 'GPS', 'SoftwareSerial'],
                'applications' => ['Vehicle tracking', 'Navigation', 'Geofencing', 'Asset tracking', 'Timing'],
                'limitations' => ['Requires clear sky view', 'Slow cold start', 'Affected by urban canyons'],
                'safety_notes'=> 'Standard electronic component. No special safety concerns.',
            ],
            [
                'sensor_type' => 'nrf24l01',
                'display_name' => 'NRF24L01+ Wireless Transceiver',
                'function_description' => '2.4GHz wireless transceiver for short-range communication.',
                'input_output_type' => 'Digital',
                'voltage_range' => '1.9-3.6V',
                'current_consumption' => '11.3mA (TX), 13.5mA (RX)',
                'interface' => 'SPI',
                'range' => '100m (open air), 1-2km with PA+LNA',
                'accuracy' => 'N/A (communication)',
                'resolution' => 'N/A',
                'response_time' => '250µs switching',
                'operating_conditions' => '-40°C to 85°C',
                'calibration_notes' => 'No calibration required. Antenna selection affects range.',
                'compatible_controllers' => ['Arduino', 'ESP32', 'Raspberry Pi', 'STM32'],
                'compatible_libraries' => ['RF24', 'nRF24L01'],
                'applications' => ['Wireless sensor networks', 'Remote control', 'IoT communication', 'Data logging'],
                'limitations' => ['Limited range without PA', '2.4GHz interference', '1.9-3.6V only'],
                'safety_notes'=> 'Low power RF device. Safe for all applications.',
            ],
            [
                'sensor_type' => 'hx711_load_cell',
                'display_name' => 'HX711 Load Cell Amplifier',
                'function_description' => '24-bit ADC for weight/load measurement with load cell.',
                'input_output_type' => 'Digital',
                'voltage_range' => '2.6-5.5V',
                'current_consumption' => '1.5mA',
                'interface' => 'Serial (clock + data)',
                'range' => 'Dependent on load cell (typically 0-50kg)',
                'accuracy' => '±0.05% of full scale',
                'resolution' => '24-bit',
                'response_time' => '10Hz sampling',
                'operating_conditions' => '-40°C to 85°C',
                'calibration_notes' => 'Requires calibration with known weight. Tare function needed.',
                'compatible_controllers' => ['Arduino', 'ESP32', 'Raspberry Pi'],
                'compatible_libraries' => ['HX711', 'HX711_ADC'],
                'applications' => ['Digital scales', 'Weight measurement', 'Force sensing', 'Inventory counting'],
                'limitations' => ['Requires load cell', 'Temperature drift', 'Slow sampling rate'],
                'safety_notes'=> 'Standard electronic component. Handle load cell with care.',
            ],
            [
                'sensor_type' => 'bh1750',
                'display_name' => 'BH1750 Digital Light Intensity Sensor',
                'function_description' => 'Digital ambient light sensor with I2C interface.',
                'input_output_type' => 'Digital',
                'voltage_range' => '2.4-3.6V',
                'current_consumption' => '120µA',
                'interface' => 'I2C',
                'range' => '1-65535 lux',
                'accuracy' => '±20%',
                'resolution' => '1 lux',
                'response_time' => '120ms',
                'operating_conditions' => '-40°C to 85°C',
                'calibration_notes' => 'No calibration required. One-time measurement mode recommended.',
                'compatible_controllers' => ['Arduino', 'ESP32', 'Raspberry Pi', 'STM32'],
                'compatible_libraries' => ['BH1750', 'Wire'],
                'applications' => ['Smart lighting', 'Agriculture', 'Display brightness', 'Solar tracking'],
                'limitations' => ['Spectral response differs from human eye', 'Affected by direct sunlight'],
                'safety_notes'=> 'Standard electronic component handling.',
            ],
        ];

        foreach ($sensors as $sensor) {
            SensorKnowledge::updateOrCreate(
                ['sensor_type' => $sensor['sensor_type']],
                $sensor
            );
        }

        $this->command->info('Seeded ' . count($sensors) . ' sensors.');
    }

    private function seedProjects(): void
    {
        $projects = [
            [
                'title' => '4WD Obstacle-Avoiding Robot',
                'slug' => '4wd-obstacle-avoiding-robot',
                'summary' => 'Build a four-wheel-drive robot that autonomously navigates and avoids obstacles using ultrasonic sensors.',
                'description' => 'This project teaches robotics fundamentals including motor control, sensor integration, and autonomous navigation. The robot uses an HC-SR04 ultrasonic sensor to detect obstacles and an L298N motor driver to control four DC gear motors.',
                'category' => 'robotics',
                'subcategory' => 'autonomous',
                'skill_level' => 'beginner',
                'age_group' => '10-16',
                'grade_level' => 'Grade 6-10',
                'estimated_duration_minutes' => 180,
                'estimated_cost' => 45.00,
                'currency' => 'USD',
                'learning_outcomes' => 'Motor control, sensor integration, autonomous navigation, basic programming, circuit building',
                'required_prior_knowledge' => 'Basic electronics, basic programming concepts',
                'main_controller' => 'Arduino',
                'supported_controllers' => ['Arduino Uno', 'Arduino Nano', 'ESP32'],
                'sensor_types' => ['ultrasonic', 'ir'],
                'actuator_types' => ['dc_motor', 'servo'],
                'communication_methods' => ['bluetooth_optional'],
                'power_requirements' => '7.4V 2S LiPo battery or 6x AA batteries',
                'tools_required' => 'Soldering iron, screwdriver, wire strippers, multimeter',
                'safety_warnings' => 'Do not leave battery charging unattended. Keep fingers away from moving parts. Supervise younger students.',
                'wiring_instructions' => 'Connect L298N motor driver IN1-IN4 to Arduino digital pins 5,6,7,8. Connect ENA/ENB to PWM pins 9,10. Connect HC-SR04 TRIG to pin 2, ECHO to pin 3. Connect battery to L298N 12V input.',
                'pin_mapping' => [
                    ['component' => 'L298N IN1', 'pin' => 'D5', 'controller_pin' => 'Digital 5'],
                    ['component' => 'L298N IN2', 'pin' => 'D6', 'controller_pin' => 'Digital 6'],
                    ['component' => 'L298N IN3', 'pin' => 'D7', 'controller_pin' => 'Digital 7'],
                    ['component' => 'L298N IN4', 'pin' => 'D8', 'controller_pin' => 'Digital 8'],
                    ['component' => 'HC-SR04 TRIG', 'pin' => 'D2', 'controller_pin' => 'Digital 2'],
                    ['component' => 'HC-SR04 ECHO', 'pin' => 'D3', 'controller_pin' => 'Digital 3'],
                ],
                'assembly_steps' => "1. Mount motors on chassis\n2. Attach wheels to motors\n3. Mount L298N motor driver\n4. Connect motors to L298N\n5. Mount Arduino on chassis\n6. Connect L298N to Arduino\n7. Mount HC-SR04 sensor at front\n8. Connect sensor to Arduino\n9. Connect battery\n10. Upload code and test",
                'testing_procedure' => '1. Power on robot\n2. Place obstacle 30cm in front\n3. Robot should detect and turn\n4. Test with different obstacle distances\n5. Verify motor direction is correct',
                'calibration_procedure' => '1. Adjust ultrasonic sensor angle for optimal detection\n2. Test obstacle detection range\n3. Fine-tune motor speed if robot pulls to one side',
                'troubleshooting' => '1. Robot does not move: Check motor connections and battery\n2. Robot turns in circles: Check sensor connections\n3. Obstacles not detected: Verify sensor angle and connections\n4. Robot moves backward: Swap motor wires',
                'expected_output' => 'Robot autonomously navigates, detects obstacles 20-30cm ahead, and turns to avoid them.',
                'verification_status' => 'published',
                'is_featured' => true,
            ],
            [
                'title' => 'ESP32 Weather Station',
                'slug' => 'esp32-weather-station',
                'summary' => 'Build a WiFi-connected weather station that measures temperature, humidity, and pressure.',
                'description' => 'This project creates a complete weather monitoring system using ESP32 and DHT22/BMP280 sensors. Data is displayed on an OLED screen and can be uploaded to the cloud.',
                'category' => 'iot',
                'subcategory' => 'weather',
                'skill_level' => 'beginner',
                'age_group' => '12-18',
                'grade_level' => 'Grade 7-12',
                'estimated_duration_minutes' => 120,
                'estimated_cost' => 25.00,
                'currency' => 'USD',
                'learning_outcomes' => 'IoT concepts, sensor integration, WiFi communication, data display, cloud connectivity',
                'required_prior_knowledge' => 'Basic programming, basic electronics',
                'main_controller' => 'ESP32',
                'supported_controllers' => ['ESP32', 'ESP32-S3', 'Arduino with WiFi shield'],
                'sensor_types' => ['temperature', 'humidity', 'pressure'],
                'actuator_types' => ['oled_display'],
                'communication_methods' => ['wifi', 'bluetooth'],
                'power_requirements' => '5V USB or 3.7V LiPo with boost converter',
                'tools_required' => 'Soldering iron, breadboard, jumper wires',
                'safety_warnings' => 'Low voltage project. Safe for supervised student use.',
                'wiring_instructions' => 'Connect DHT22 DATA to GPIO4, VCC to 3.3V, GND to GND. Connect BMP280 SDA to GPIO21, SCL to GPIO22. Connect OLED SDA to GPIO21, SCL to GPIO22 (shared I2C bus).',
                'pin_mapping' => [
                    ['component' => 'DHT22 DATA', 'pin' => 'GPIO4', 'controller_pin' => 'GPIO 4'],
                    ['component' => 'BMP280 SDA', 'pin' => 'GPIO21', 'controller_pin' => 'GPIO 21 (I2C)'],
                    ['component' => 'BMP280 SCL', 'pin' => 'GPIO22', 'controller_pin' => 'GPIO 22 (I2C)'],
                    ['component' => 'OLED SDA', 'pin' => 'GPIO21', 'controller_pin' => 'GPIO 21 (I2C)'],
                    ['component' => 'OLED SCL', 'pin' => 'GPIO22', 'controller_pin' => 'GPIO 22 (I2C)'],
                ],
                'assembly_steps' => "1. Connect DHT22 to ESP32\n2. Connect BMP280 to ESP32\n3. Connect OLED display\n4. Connect power supply\n5. Upload Arduino IDE code\n6. Configure WiFi credentials\n7. Test sensor readings\n8. Display on OLED\n9. Optional: Upload to cloud",
                'testing_procedure' => '1. Power on station\n2. Verify WiFi connection\n3. Check sensor readings on OLED\n4. Compare with reference thermometer\n5. Test cloud upload if configured',
                'calibration_procedure' => '1. Compare temperature reading with calibrated thermometer\n2. Adjust offset if needed in code\n3. Verify pressure reading at sea level',
                'troubleshooting' => '1. No WiFi connection: Check SSID/password in code\n2. Sensor not reading: Verify wiring and power\n3. OLED not displaying: Check I2C address (0x3C or 0x3D)\n4. Inaccurate readings: Allow 2-3 minutes for sensor stabilization',
                'expected_output' => 'Weather station displays temperature, humidity, and pressure on OLED. Optional: data uploaded to cloud dashboard.',
                'verification_status' => 'published',
                'is_featured' => true,
            ],
            [
                'title' => 'Smart Irrigation System',
                'slug' => 'smart-irrigation-system',
                'summary' => 'Automated plant watering system using soil moisture sensors and a water pump.',
                'description' => 'This project creates an intelligent irrigation system that monitors soil moisture and automatically waters plants when needed. Uses ESP32 for WiFi connectivity and data logging.',
                'category' => 'agriculture',
                'subcategory' => 'irrigation',
                'skill_level' => 'intermediate',
                'age_group' => '12-18',
                'grade_level' => 'Grade 8-12',
                'estimated_duration_minutes' => 150,
                'estimated_cost' => 35.00,
                'currency' => 'USD',
                'learning_outcomes' => 'Agricultural IoT, sensor calibration, relay control, water management, data logging',
                'required_prior_knowledge' => 'Basic electronics, basic programming, understanding of soil moisture',
                'main_controller' => 'ESP32',
                'supported_controllers' => ['ESP32', 'Arduino Uno'],
                'sensor_types' => ['soil_moisture', 'temperature'],
                'actuator_types' => ['relay', 'pump'],
                'communication_methods' => ['wifi'],
                'power_requirements' => '12V DC adapter for pump, 5V for electronics',
                'tools_required' => 'Soldering iron, screwdriver, tubing, waterproof enclosure',
                'safety_warnings' => 'Keep electronics away from water. Use waterproof enclosure for outdoor installations. Supervise water pump operation.',
                'wiring_instructions' => 'Connect soil moisture sensor to ADC pin (GPIO34). Connect relay module to GPIO25. Connect pump to relay. Connect power supplies.',
                'pin_mapping' => [
                    ['component' => 'Soil Moisture Sensor', 'pin' => 'ADC', 'controller_pin' => 'GPIO 34 (ADC1)'],
                    ['component' => 'Relay Module', 'pin' => 'IN', 'controller_pin' => 'GPIO 25'],
                    ['component' => 'Status LED', 'pin' => 'D2', 'controller_pin' => 'GPIO 2'],
                ],
                'assembly_steps' => "1. Calibrate soil moisture sensor\n2. Connect sensor to ESP32\n3. Connect relay module\n4. Connect water pump to relay\n5. Connect power supplies\n6. Upload code with WiFi credentials\n7. Set moisture threshold\n8. Test pump activation\n9. Install in garden/plant pot",
                'testing_procedure' => '1. Place sensor in dry soil - pump should activate\n2. Place sensor in wet soil - pump should stop\n3. Check WiFi data logging\n4. Test manual override',
                'calibration_procedure' => '1. Read ADC value in dry air (min value)\n2. Read ADC value in water (max value)\n3. Set threshold between dry and wet values\n4. Adjust hysteresis to prevent rapid cycling',
                'troubleshooting' => '1. Pump does not activate: Check relay connections and power\n2. Inaccurate moisture reading: Recalibrate sensor\n3. WiFi disconnects: Check signal strength, add reconnect logic\n4. Pump runs continuously: Adjust threshold and hysteresis',
                'expected_output' => 'System monitors soil moisture and automatically waters plants when moisture drops below threshold. Data logged to cloud.',
                'verification_status' => 'published',
                'is_featured' => true,
            ],
            [
                'title' => 'RFID Attendance System',
                'slug' => 'rfid-attendance-system',
                'summary' => 'Build an RFID-based attendance tracking system with OLED display and data logging.',
                'description' => 'This project creates an attendance system using RFID cards. Students tap their cards to log attendance, which is displayed on screen and stored for reporting.',
                'category' => 'security',
                'subcategory' => 'attendance',
                'skill_level' => 'intermediate',
                'age_group' => '14-18',
                'grade_level' => 'Grade 9-12',
                'estimated_duration_minutes' => 180,
                'estimated_cost' => 30.00,
                'currency' => 'USD',
                'learning_outcomes' => 'RFID technology, database management, user interface design, system integration',
                'required_prior_knowledge' => 'Basic programming, basic database concepts',
                'main_controller' => 'Arduino',
                'supported_controllers' => ['Arduino Uno', 'Arduino Mega', 'ESP32'],
                'sensor_types' => ['rfid'],
                'actuator_types' => ['oled_display', 'buzzer', 'led'],
                'communication_methods' => ['serial'],
                'power_requirements' => '5V USB or 9V DC adapter',
                'tools_required' => 'Soldering iron, breadboard, jumper wires',
                'safety_warnings' => 'Standard electronics safety. Keep RFID cards away from magnetic sources.',
                'wiring_instructions' => 'Connect RC522 SDA→D10, SCK→D13, MOSI→D11, MISO→D12, RST→D9. Connect OLED SDA→A4, SCL→A5. Connect buzzer to D7, LED to D6.',
                'pin_mapping' => [
                    ['component' => 'RC522 SDA', 'pin' => 'D10', 'controller_pin' => 'Digital 10 (SS)'],
                    ['component' => 'RC522 SCK', 'pin' => 'D13', 'controller_pin' => 'Digital 13 (SCK)'],
                    ['component' => 'RC522 MOSI', 'pin' => 'D11', 'controller_pin' => 'Digital 11 (MOSI)'],
                    ['component' => 'RC522 MISO', 'pin' => 'D12', 'controller_pin' => 'Digital 12 (MISO)'],
                    ['component' => 'OLED SDA', 'pin' => 'A4', 'controller_pin' => 'Analog 4 (SDA)'],
                    ['component' => 'Buzzer', 'pin' => 'D7', 'controller_pin' => 'Digital 7'],
                ],
                'assembly_steps' => "1. Connect RC522 to Arduino via SPI\n2. Connect OLED display via I2C\n3. Connect buzzer and LED\n4. Upload code\n5. Register RFID cards\n6. Test card reading\n7. Test attendance logging\n8. Verify display output",
                'testing_procedure' => '1. Power on system\n2. Tap registered card - should show name and log attendance\n3. Tap unregistered card - should show "Unknown"\n4. Check serial monitor for log data\n5. Verify attendance records are saved',
                'calibration_procedure' => '1. Register test RFID cards\n2. Verify read range (typically 3-5cm)\n3. Adjust antenna orientation if needed',
                'troubleshooting' => '1. Card not reading: Check SPI connections\n2. OLED not displaying: Verify I2C address\n3. Buzzer not working: Check connection and polarity\n4. Incorrect card ID: Verify RFID library version',
                'expected_output' => 'Students tap RFID cards to log attendance. System displays name, logs time, and stores records.',
                'verification_status' => 'published',
                'is_featured' => false,
            ],
            [
                'title' => 'Line-Following Robot',
                'slug' => 'line-following-robot',
                'summary' => 'Build a robot that follows a black line on a white surface using IR sensors.',
                'description' => 'Classic robotics project using IR sensors to detect a line and PID or simple logic to follow it. Great introduction to feedback control systems.',
                'category' => 'robotics',
                'subcategory' => 'line_follower',
                'skill_level' => 'beginner',
                'age_group' => '10-16',
                'grade_level' => 'Grade 5-10',
                'estimated_duration_minutes' => 120,
                'estimated_cost' => 35.00,
                'currency' => 'USD',
                'learning_outcomes' => 'Motor control, IR sensing, PID basics, robot navigation, problem solving',
                'required_prior_knowledge' => 'Basic programming, basic electronics',
                'main_controller' => 'Arduino',
                'supported_controllers' => ['Arduino Uno', 'Arduino Nano'],
                'sensor_types' => ['ir_obstacle'],
                'actuator_types' => ['dc_motor'],
                'communication_methods' => ['none'],
                'power_requirements' => '7.4V 2S LiPo or 4x AA batteries',
                'tools_required' => 'Soldering iron, screwdriver, black electrical tape',
                'safety_warnings' => 'Keep fingers away from wheels. Supervise battery charging.',
                'wiring_instructions' => 'Connect 2-3 IR sensors to analog pins A0-A2. Connect motor driver to digital pins. Connect motors to driver.',
                'pin_mapping' => [
                    ['component' => 'Left IR Sensor', 'pin' => 'A0', 'controller_pin' => 'Analog 0'],
                    ['component' => 'Center IR Sensor', 'pin' => 'A1', 'controller_pin' => 'Analog 1'],
                    ['component' => 'Right IR Sensor', 'pin' => 'A2', 'controller_pin' => 'Analog 2'],
                    ['component' => 'Motor Driver', 'pin' => 'D5-D8', 'controller_pin' => 'Digital 5-8'],
                ],
                'assembly_steps' => "1. Mount motors on chassis\n2. Attach wheels\n3. Mount IR sensors at front\n4. Connect sensors to Arduino\n5. Connect motor driver\n6. Upload code\n7. Create test track with black tape\n8. Test and tune sensors",
                'testing_procedure' => '1. Place robot on white surface with black line\n2. Robot should follow the line\n3. Test at different speeds\n4. Test sharp turns',
                'calibration_procedure' => '1. Place sensor over white surface - note analog value\n2. Place sensor over black line - note analog value\n3. Set threshold between values',
                'troubleshooting' => '1. Robot goes off track: Adjust sensor threshold\n2. Robot oscillates: Reduce speed or adjust PID\n3. Robot does not move: Check motor connections',
                'expected_output' => 'Robot follows a black line on white surface at moderate speed.',
                'verification_status' => 'published',
                'is_featured' => true,
            ],
            [
                'title' => 'GPS Vehicle Tracker',
                'slug' => 'gps-vehicle-tracker',
                'summary' => 'Real-time vehicle tracking system using GPS and GSM modules with web dashboard.',
                'description' => 'Track vehicles in real-time using GPS for location and GSM for data transmission. View location on a web dashboard.',
                'category' => 'iot',
                'subcategory' => 'tracking',
                'skill_level' => 'advanced',
                'age_group' => '16-18',
                'grade_level' => 'Grade 11-12',
                'estimated_duration_minutes' => 240,
                'estimated_cost' => 55.00,
                'currency' => 'USD',
                'learning_outcomes' => 'GPS technology, GSM communication, web integration, data visualization, system design',
                'required_prior_knowledge' => 'Programming, electronics, basic networking',
                'main_controller' => 'Arduino',
                'supported_controllers' => ['Arduino Mega', 'ESP32'],
                'sensor_types' => ['gps'],
                'actuator_types' => ['gsm_modem'],
                'communication_methods' => ['gsm', 'gps'],
                'power_requirements' => '12V vehicle power with voltage regulator',
                'tools_required' => 'Soldering iron, multimeter, SIM card with data plan',
                'safety_warnings' => 'Install in well-ventilated area. Do not obstruct vehicle controls. Professional installation recommended.',
                'wiring_instructions' => 'Connect GPS module TX→D2, RX→D3. Connect GSM module TX→D7, RX→D8. Connect power with voltage regulator.',
                'pin_mapping' => [
                    ['component' => 'GPS TX', 'pin' => 'D2', 'controller_pin' => 'Digital 2 (SoftwareSerial RX)'],
                    ['component' => 'GPS RX', 'pin' => 'D3', 'controller_pin' => 'Digital 3 (SoftwareSerial TX)'],
                    ['component' => 'GSM TX', 'pin' => 'D7', 'controller_pin' => 'Digital 7 (SoftwareSerial RX)'],
                    ['component' => 'GSM RX', 'pin' => 'D8', 'controller_pin' => 'Digital 8 (SoftwareSerial TX)'],
                ],
                'assembly_steps' => "1. Connect GPS module\n2. Connect GSM module\n3. Insert SIM card\n4. Connect power with regulator\n5. Upload tracking code\n6. Configure server URL\n7. Test GPS fix\n8. Test SMS/data transmission\n9. Install in vehicle",
                'testing_procedure' => '1. Power on and wait for GPS fix (2-5 min)\n2. Verify location data on serial monitor\n3. Test SMS sending\n4. Verify data on web dashboard\n5. Test in moving vehicle',
                'calibration_procedure' => '1. Ensure GPS antenna has clear sky view\n2. Test GSM signal strength\n3. Configure APN settings for SIM card',
                'troubleshooting' => '1. No GPS fix: Check antenna placement, wait longer\n2. No GSM signal: Check SIM card, antenna, power\n3. Data not sending: Verify APN and server URL\n4. Inaccurate location: Allow warm-up time, check antenna',
                'expected_output' => 'Vehicle location tracked in real-time via GPS, transmitted via GSM, displayed on web dashboard.',
                'verification_status' => 'published',
                'is_featured' => false,
            ],
            [
                'title' => 'Smart Home Automation Hub',
                'slug' => 'smart-home-automation-hub',
                'summary' => 'Control lights, fans, and appliances from your phone using ESP32 and relays.',
                'description' => 'Build a home automation system that allows controlling electrical appliances via a mobile app. Uses ESP32 WiFi and relay modules.',
                'category' => 'automation',
                'subcategory' => 'home',
                'skill_level' => 'intermediate',
                'age_group' => '14-18',
                'grade_level' => 'Grade 9-12',
                'estimated_duration_minutes' => 180,
                'estimated_cost' => 40.00,
                'currency' => 'USD',
                'learning_outcomes' => 'Home automation, relay control, mobile app development, WiFi communication, electrical safety',
                'required_prior_knowledge' => 'Basic programming, basic electronics, electrical safety awareness',
                'main_controller' => 'ESP32',
                'supported_controllers' => ['ESP32', 'ESP8266'],
                'sensor_types' => ['temperature', 'light'],
                'actuator_types' => ['relay', 'led'],
                'communication_methods' => ['wifi', 'bluetooth'],
                'power_requirements' => '5V for ESP32, 12V/24V for relay loads',
                'tools_required' => 'Soldering iron, multimeter, screwdriver, electrical tape',
                'safety_warnings' => 'DANGER: High voltage when controlling mains appliances. Only qualified electricians should handle mains wiring. Use proper enclosures. Disconnect power before modifications.',
                'wiring_instructions' => 'Connect ESP32 GPIO pins to relay IN1-IN4. Connect relay COM/NO terminals to loads. Connect 5V power to ESP32, 12V/24V to relay module.',
                'pin_mapping' => [
                    ['component' => 'Relay 1', 'pin' => 'GPIO25', 'controller_pin' => 'GPIO 25'],
                    ['component' => 'Relay 2', 'pin' => 'GPIO26', 'controller_pin' => 'GPIO 26'],
                    ['component' => 'Relay 3', 'pin' => 'GPIO27', 'controller_pin' => 'GPIO 27'],
                    ['component' => 'Relay 4', 'pin' => 'GPIO14', 'controller_pin' => 'GPIO 14'],
                    ['component' => 'Status LED', 'pin' => 'GPIO2', 'controller_pin' => 'GPIO 2'],
                ],
                'assembly_steps' => "1. Connect ESP32 to relay module\n2. Connect power supplies\n3. Upload firmware\n4. Configure WiFi\n5. Set up mobile app\n6. Test low-voltage control first\n7. Install proper enclosures\n8. Professional mains wiring (if applicable)",
                'testing_procedure' => '1. Test WiFi connection\n2. Test relay switching with LED\n3. Test mobile app control\n4. Test timer/schedule functions\n5. Verify all safety features',
                'calibration_procedure' => '1. Set WiFi credentials\n2. Configure relay timing\n3. Set device names in app',
                'troubleshooting' => '1. WiFi not connecting: Check credentials, signal strength\n2. Relay not switching: Check connections, power\n3. App not connecting: Verify network, firewall settings',
                'expected_output' => 'Control up to 4 electrical devices via mobile app. Support for timers and schedules.',
                'verification_status' => 'published',
                'is_featured' => true,
            ],
        ];

        foreach ($projects as $projectData) {
            $project = EducationProject::updateOrCreate(
                ['slug' => $projectData['slug']],
                array_merge($projectData, [
                    'view_count' => rand(50, 500),
                    'rating_avg' => rand(35, 50) / 10,
                    'rating_count' => rand(5, 50),
                ])
            );

            // Create BOM lines
            $this->createBomLines($project->id, $projectData['category']);
        }

        $this->command->info('Seeded ' . count($projects) . ' education projects.');
    }

    private function createBomLines(int $projectId, string $category): void
    {
        $bomTemplates = [
            'robotics' => [
                ['component_role' => 'Main Controller', 'preferred_mpn' => 'ATMEGA328P', 'quantity' => 1, 'is_required' => true],
                ['component_role' => 'Motor Driver', 'preferred_mpn' => 'L298N', 'quantity' => 1, 'is_required' => true],
                ['component_role' => 'DC Motor', 'preferred_mpn' => 'DC-3V-6V', 'quantity' => 4, 'is_required' => true],
                ['component_role' => 'Wheel', 'preferred_mpn' => 'ROBOT-WHEEL-65MM', 'quantity' => 4, 'is_required' => true],
                ['component_role' => 'Chassis', 'preferred_mpn' => '4WD-CHASSIS', 'quantity' => 1, 'is_required' => true],
                ['component_role' => 'Battery', 'preferred_mpn' => 'LIPO-7.4V', 'quantity' => 1, 'is_required' => true],
                ['component_role' => 'Jumper Wires', 'preferred_mpn' => 'JUMPER-WIRE-40PIN', 'quantity' => 1, 'is_required' => true],
                ['component_role' => 'Sensor', 'preferred_mpn' => 'HC-SR04', 'quantity' => 1, 'is_required' => false],
            ],
            'iot' => [
                ['component_role' => 'Main Controller', 'preferred_mpn' => 'ESP32-WROOM', 'quantity' => 1, 'is_required' => true],
                ['component_role' => 'Breadboard', 'preferred_mpn' => 'BREADBOARD-830', 'quantity' => 1, 'is_required' => true],
                ['component_role' => 'Jumper Wires', 'preferred_mpn' => 'JUMPER-WIRE-40PIN', 'quantity' => 1, 'is_required' => true],
                ['component_role' => 'LED', 'preferred_mpn' => 'LED-5MM-RED', 'quantity' => 5, 'is_required' => true],
                ['component_role' => 'Resistor', 'preferred_mpn' => 'RES-220OHM-0402', 'quantity' => 5, 'is_required' => true],
                ['component_role' => 'Power Supply', 'preferred_mpn' => 'USB-5V-2A', 'quantity' => 1, 'is_required' => true],
            ],
            'agriculture' => [
                ['component_role' => 'Main Controller', 'preferred_mpn' => 'ESP32-WROOM', 'quantity' => 1, 'is_required' => true],
                ['component_role' => 'Soil Moisture Sensor', 'preferred_mpn' => 'SOIL-MOISTURE-V2', 'quantity' => 2, 'is_required' => true],
                ['component_role' => 'Relay Module', 'preferred_mpn' => 'RELAY-4CH', 'quantity' => 1, 'is_required' => true],
                ['component_role' => 'Water Pump', 'preferred_mpn' => 'PUMP-DC-5V', 'quantity' => 1, 'is_required' => true],
                ['component_role' => 'Tubing', 'preferred_mpn' => 'TUBING-8MM', 'quantity' => 1, 'is_required' => true],
                ['component_role' => 'Power Supply', 'preferred_mpn' => 'PSU-12V-2A', 'quantity' => 1, 'is_required' => true],
            ],
            'security' => [
                ['component_role' => 'Main Controller', 'preferred_mpn' => 'ATMEGA328P', 'quantity' => 1, 'is_required' => true],
                ['component_role' => 'RFID Reader', 'preferred_mpn' => 'RC522', 'quantity' => 1, 'is_required' => true],
                ['component_role' => 'RFID Cards', 'preferred_mpn' => 'MIFARE-1K', 'quantity' => 5, 'is_required' => true],
                ['component_role' => 'OLED Display', 'preferred_mpn' => 'OLED-128X64', 'quantity' => 1, 'is_required' => true],
                ['component_role' => 'Buzzer', 'preferred_mpn' => 'BUZZER-5V', 'quantity' => 1, 'is_required' => true],
                ['component_role' => 'LED', 'preferred_mpn' => 'LED-5MM-GREEN', 'quantity' => 3, 'is_required' => true],
            ],
            'default' => [
                ['component_role' => 'Main Controller', 'preferred_mpn' => 'ATMEGA328P', 'quantity' => 1, 'is_required' => true],
                ['component_role' => 'Breadboard', 'preferred_mpn' => 'BREADBOARD-830', 'quantity' => 1, 'is_required' => true],
                ['component_role' => 'Jumper Wires', 'preferred_mpn' => 'JUMPER-WIRE-40PIN', 'quantity' => 1, 'is_required' => true],
                ['component_role' => 'LED', 'preferred_mpn' => 'LED-5MM-RED', 'quantity' => 5, 'is_required' => true],
                ['component_role' => 'Resistor', 'preferred_mpn' => 'RES-220OHM-0402', 'quantity' => 10, 'is_required' => true],
                ['component_role' => 'Power Supply', 'preferred_mpn' => 'USB-5V-2A', 'quantity' => 1, 'is_required' => true],
            ],
        ];

        $bomLines = $bomTemplates[$category] ?? $bomTemplates['default'];

        foreach ($bomLines as $index => $line) {
            BomLine::create(array_merge($line, [
                'education_project_id' => $projectId,
                'line_no' => $index + 1,
            ]));
        }
    }
}
