<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class WarehouseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $warehouses = [
            [
                'id' => Str::uuid(),
                'name' => 'Shenzhen Global Distribution Center',
                'code' => 'SZX-GDC',
                'type' => 'global_distribution',
                'address_line_1' => 'Qianhai Shenzhen-Hong Kong Modern Service Industry Cooperation Zone',
                'address_line_2' => 'Building A, Logistics Park',
                'city' => 'Shenzhen',
                'state_province' => 'Guangdong',
                'postal_code' => '518000',
                'country' => 'CN',
                'country_name' => 'China',
                'region' => 'East Asia',
                'latitude' => 22.5431,
                'longitude' => 114.0579,
                'capacity_units' => 100000,
                'current_stock_units' => 0,
                'manager_name' => null,
                'manager_email' => null,
                'manager_phone' => '+86-755-XXX-XXXX',
                'operating_hours_start' => '08:00',
                'operating_hours_end' => '22:00',
                'timezone' => 'Asia/Shanghai',
                'is_active' => true,
                'is_primary' => false,
                'supports_cross_border' => true,
                'customs_clearance_enabled' => true,
                'cold_storage_available' => true,
                'hazmat_certified' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(),
                'name' => 'Delhi Regional Distribution Center',
                'code' => 'DEL-RDC',
                'type' => 'regional_distribution',
                'address_line_1' => 'National Capital Region Warehouse Complex',
                'address_line_2' => 'Sector 18, Industrial Area',
                'city' => 'New Delhi',
                'state_province' => 'Delhi',
                'postal_code' => '110020',
                'country' => 'IN',
                'country_name' => 'India',
                'region' => 'South Asia',
                'latitude' => 28.6139,
                'longitude' => 77.2090,
                'capacity_units' => 75000,
                'current_stock_units' => 0,
                'manager_name' => null,
                'manager_email' => null,
                'manager_phone' => '+91-11-XXXX-XXXX',
                'operating_hours_start' => '09:00',
                'operating_hours_end' => '21:00',
                'timezone' => 'Asia/Kolkata',
                'is_active' => true,
                'is_primary' => false,
                'supports_cross_border' => true,
                'customs_clearance_enabled' => true,
                'cold_storage_available' => true,
                'hazmat_certified' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(),
                'name' => 'Kathmandu Main Distribution Center',
                'code' => 'KTM-MDC',
                'type' => 'main_distribution',
                'address_line_1' => 'Balkhu Industrial Area',
                'address_line_2' => 'Warehouse Complex, Building 3',
                'city' => 'Kathmandu',
                'state_province' => 'Bagmati',
                'postal_code' => '44600',
                'country' => 'NP',
                'country_name' => 'Nepal',
                'region' => 'South Asia',
                'latitude' => 27.6710,
                'longitude' => 85.4298,
                'capacity_units' => 50000,
                'current_stock_units' => 0,
                'manager_name' => null,
                'manager_email' => null,
                'manager_phone' => '+977-1-XXXXXXX',
                'operating_hours_start' => '08:00',
                'operating_hours_end' => '20:00',
                'timezone' => 'Asia/Kathmandu',
                'is_active' => true,
                'is_primary' => true,
                'supports_cross_border' => true,
                'customs_clearance_enabled' => true,
                'cold_storage_available' => false,
                'hazmat_certified' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(),
                'name' => 'Colombo Regional Distribution Center',
                'code' => 'CMB-RDC',
                'type' => 'regional_distribution',
                'address_line_1' => 'Port City Commercial Complex',
                'address_line_2' => 'Zone B, Logistics Hub',
                'city' => 'Colombo',
                'state_province' => 'Western Province',
                'postal_code' => '00100',
                'country' => 'LK',
                'country_name' => 'Sri Lanka',
                'region' => 'South Asia',
                'latitude' => 6.9271,
                'longitude' => 79.8612,
                'capacity_units' => 40000,
                'current_stock_units' => 0,
                'manager_name' => null,
                'manager_email' => null,
                'manager_phone' => '+94-11-XXX-XXXX',
                'operating_hours_start' => '08:30',
                'operating_hours_end' => '19:30',
                'timezone' => 'Asia/Colombo',
                'is_active' => true,
                'is_primary' => false,
                'supports_cross_border' => true,
                'customs_clearance_enabled' => true,
                'cold_storage_available' => true,
                'hazmat_certified' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(),
                'name' => 'Dubai Distribution Center',
                'code' => 'DXB-DC',
                'type' => 'regional_distribution',
                'address_line_1' => 'Jebel Ali Free Zone (JAFZA)',
                'address_line_2' => 'South Zone, Plot S-40123',
                'city' => 'Dubai',
                'state_province' => 'Dubai',
                'postal_code' => '17027',
                'country' => 'AE',
                'country_name' => 'United Arab Emirates',
                'region' => 'Middle East',
                'latitude' => 24.9857,
                'longitude' => 55.0272,
                'capacity_units' => 80000,
                'current_stock_units' => 0,
                'manager_name' => null,
                'manager_email' => null,
                'manager_phone' => '+971-4-XXX-XXXX',
                'operating_hours_start' => '08:00',
                'operating_hours_end' => '20:00',
                'timezone' => 'Asia/Dubai',
                'is_active' => true,
                'is_primary' => false,
                'supports_cross_border' => true,
                'customs_clearance_enabled' => true,
                'cold_storage_available' => true,
                'hazmat_certified' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        // Insert or update warehouses
        foreach ($warehouses as $warehouse) {
            DB::table('warehouses')->updateOrInsert(
                ['code' => $warehouse['code']],
                $warehouse
            );
        }
    }
}
